-- Avaliações de serviço (1–5 estrelas) feitas pelo tutor após atendimento concluído ou vacinação.

CREATE TABLE IF NOT EXISTS flutz.avaliacao (
  avaliacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  cliente_id INT NOT NULL,
  nota DECIMAL(2,1) NOT NULL,
  comentario TEXT NULL,
  atendimento_id INT NULL,
  historico_vacinacao_id INT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_avaliacao_id PRIMARY KEY (avaliacao_id),
  CONSTRAINT chk_avaliacao_servico_nota
    CHECK (nota >= 1 AND nota <= 5),
  CONSTRAINT chk_avaliacao_servico_origem
    CHECK (
      (atendimento_id IS NOT NULL AND historico_vacinacao_id IS NULL)
      OR (atendimento_id IS NULL AND historico_vacinacao_id IS NOT NULL)
    ),
  CONSTRAINT fk_avaliacao_servico_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES flutz.empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_avaliacao_servico_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES flutz.cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_avaliacao_servico_atendimento
    FOREIGN KEY (atendimento_id)
    REFERENCES flutz.atendimento (atendimento_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_avaliacao_servico_vacina
    FOREIGN KEY (historico_vacinacao_id)
    REFERENCES flutz.historico_vacinacao (historico_vacinacao_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_avaliacao_atendimento
  ON flutz.avaliacao (atendimento_id)
  WHERE atendimento_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_avaliacao_vacinacao
  ON flutz.avaliacao (historico_vacinacao_id)
  WHERE historico_vacinacao_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_avaliacao_empresa_data ON flutz.avaliacao (empresa_id, data_criacao DESC);
CREATE INDEX IF NOT EXISTS idx_avaliacao_cliente ON flutz.avaliacao (cliente_id);

DROP TRIGGER IF EXISTS trg_avaliacao_ultima_atualizacao ON flutz.avaliacao;
CREATE TRIGGER trg_avaliacao_ultima_atualizacao
BEFORE UPDATE ON flutz.avaliacao
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.avaliacao IS
  'Nota 1–5 e comentário do tutor após atendimento concluído ou vacinação aplicada na clínica.';
