-- Notificações in-app + auditoria de visualização (equipe da clínica).

CREATE TABLE flutz.notificacao (
  notificacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  destinatario_tipo VARCHAR(20) NOT NULL,
  destinatario_id INT NOT NULL,
  empresa_id INT NULL,
  tipo VARCHAR(40) NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  corpo TEXT NOT NULL,
  link_path VARCHAR(500) NOT NULL,
  referencia_tipo VARCHAR(40) NULL,
  referencia_id INT NULL,
  lida BOOLEAN NOT NULL DEFAULT FALSE,
  lida_em TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  chave_unica VARCHAR(220) NULL,
  CONSTRAINT pk_notificacao PRIMARY KEY (notificacao_id),
  CONSTRAINT fk_notificacao_empresa FOREIGN KEY (empresa_id) REFERENCES flutz.empresa (empresa_id),
  CONSTRAINT chk_notificacao_destinatario CHECK (destinatario_tipo IN ('CLIENTE', 'COLABORADOR')),
  CONSTRAINT chk_notificacao_tipo CHECK (tipo IN (
    'CHAT_MENSAGEM',
    'VACINA_D3',
    'VACINA_D1',
    'AGENDA_CONFIRMADA',
    'AGENDA_CANCELADA',
    'AGENDA_RECUSADA',
    'AGENDA_SOLICITACAO',
    'ATENDIMENTO_D1',
    'ATENDIMENTO_H1'
  ))
);

CREATE UNIQUE INDEX uq_notificacao_chave ON flutz.notificacao (chave_unica)
  WHERE chave_unica IS NOT NULL;

CREATE INDEX ix_notificacao_destinatario
  ON flutz.notificacao (destinatario_tipo, destinatario_id, lida, data_criacao DESC);

CREATE INDEX ix_notificacao_empresa_tipo
  ON flutz.notificacao (empresa_id, tipo, data_criacao DESC);

CREATE TABLE flutz.notificacao_visualizacao (
  notificacao_visualizacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  notificacao_id INT NOT NULL,
  colaborador_id INT NOT NULL,
  visualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_notificacao_visualizacao PRIMARY KEY (notificacao_visualizacao_id),
  CONSTRAINT fk_notif_viz_notif FOREIGN KEY (notificacao_id) REFERENCES flutz.notificacao (notificacao_id) ON DELETE CASCADE,
  CONSTRAINT fk_notif_viz_colab FOREIGN KEY (colaborador_id) REFERENCES flutz.colaborador (colaborador_id),
  CONSTRAINT uq_notif_viz UNIQUE (notificacao_id, colaborador_id)
);

COMMENT ON TABLE flutz.notificacao IS
  'Caixa de entrada in-app (tutor e equipe). chave_unica evita lembretes duplicados.';
COMMENT ON TABLE flutz.notificacao_visualizacao IS
  'Auditoria de quem da equipe abriu a notificação (ex.: solicitação na agenda).';
