-- Pagamento obrigatório no agendamento: status, valores, conta MP da clínica e cupons.

SET search_path TO flutz;

INSERT INTO flutz.agendamento_status (codigo, descricao)
VALUES ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento')
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE flutz.agendamento
  ADD COLUMN IF NOT EXISTS valor_servico DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS valor_desconto DECIMAL(10,2) NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_cobrado DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS empresa_cupom_id INT NULL;

ALTER TABLE flutz.agendamento
  DROP CONSTRAINT IF EXISTS chk_agendamento_valor_servico;
ALTER TABLE flutz.agendamento
  ADD CONSTRAINT chk_agendamento_valor_servico
    CHECK (valor_servico IS NULL OR valor_servico >= 0);

ALTER TABLE flutz.agendamento
  DROP CONSTRAINT IF EXISTS chk_agendamento_valor_desconto;
ALTER TABLE flutz.agendamento
  ADD CONSTRAINT chk_agendamento_valor_desconto
    CHECK (valor_desconto IS NULL OR valor_desconto >= 0);

ALTER TABLE flutz.agendamento
  DROP CONSTRAINT IF EXISTS chk_agendamento_valor_cobrado;
ALTER TABLE flutz.agendamento
  ADD CONSTRAINT chk_agendamento_valor_cobrado
    CHECK (valor_cobrado IS NULL OR valor_cobrado >= 0);

COMMENT ON COLUMN flutz.agendamento.valor_servico IS
  'Snapshot do preço do serviço/vacina no momento da solicitação.';
COMMENT ON COLUMN flutz.agendamento.valor_cobrado IS
  'Valor a cobrar após cupom. Pagamento obrigatório para confirmar.';

ALTER TABLE flutz.empresa_vacina
  ADD COLUMN IF NOT EXISTS preco DECIMAL(10,2) NULL;

ALTER TABLE flutz.empresa_vacina
  DROP CONSTRAINT IF EXISTS chk_empresa_vacina_preco;
ALTER TABLE flutz.empresa_vacina
  ADD CONSTRAINT chk_empresa_vacina_preco
    CHECK (preco IS NULL OR preco >= 0);

COMMENT ON COLUMN flutz.empresa_vacina.preco IS
  'Preço cobrado na vacinação agendada. Obrigatório para solicitar.';

ALTER TABLE flutz.conta_pagamento
  ADD COLUMN IF NOT EXISTS public_key VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS access_token TEXT NULL,
  ADD COLUMN IF NOT EXISTS nome_exibicao VARCHAR(120) NULL;

COMMENT ON COLUMN flutz.conta_pagamento.public_key IS
  'Chave pública do gateway (Mercado Pago), isolada por clínica.';
COMMENT ON COLUMN flutz.conta_pagamento.access_token IS
  'Access token do gateway da clínica. Não misturar com credenciais da plataforma.';

CREATE TABLE IF NOT EXISTS flutz.empresa_cupom (
  empresa_cupom_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  codigo VARCHAR(80) NOT NULL,
  percentual_desconto DECIMAL(5,2) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_expiracao TIMESTAMP NOT NULL,
  status_id INT NOT NULL,
  usos_maximos INT NULL,
  usos_realizados INT NOT NULL DEFAULT 0,
  colaborador_criacao_id INT NULL,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_cupom_id PRIMARY KEY (empresa_cupom_id),
  CONSTRAINT uk_empresa_cupom_codigo UNIQUE (empresa_id, codigo),
  CONSTRAINT chk_empresa_cupom_percentual
    CHECK (percentual_desconto >= 0 AND percentual_desconto <= 100),
  CONSTRAINT chk_empresa_cupom_expiracao
    CHECK (data_expiracao > data_criacao),
  CONSTRAINT chk_empresa_cupom_usos_maximos
    CHECK (usos_maximos IS NULL OR usos_maximos >= 1),
  CONSTRAINT chk_empresa_cupom_usos_realizados
    CHECK (usos_realizados >= 0),
  CONSTRAINT fk_empresa_cupom_empresa
    FOREIGN KEY (empresa_id) REFERENCES empresa (empresa_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_cupom_status
    FOREIGN KEY (status_id) REFERENCES status (status_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_cupom_colaborador
    FOREIGN KEY (colaborador_criacao_id) REFERENCES colaborador (colaborador_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_empresa_cupom_empresa_status
  ON flutz.empresa_cupom (empresa_id, status_id);

CREATE TRIGGER trg_empresa_cupom_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_cupom
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_cupom IS
  'Cupom promocional da clínica para desconto no checkout do tutor.';

ALTER TABLE flutz.agendamento
  DROP CONSTRAINT IF EXISTS fk_agendamento_empresa_cupom;
ALTER TABLE flutz.agendamento
  ADD CONSTRAINT fk_agendamento_empresa_cupom
    FOREIGN KEY (empresa_cupom_id) REFERENCES empresa_cupom (empresa_cupom_id)
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE flutz.pagamento
  DROP CONSTRAINT IF EXISTS chk_pagamento_valor;
ALTER TABLE flutz.pagamento
  ADD CONSTRAINT chk_pagamento_valor
    CHECK (valor >= 0);

ALTER TABLE flutz.pagamento
  ADD COLUMN IF NOT EXISTS empresa_cupom_id INT NULL,
  ADD COLUMN IF NOT EXISTS valor_bruto DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS percentual_desconto DECIMAL(5,2) NULL,
  ADD COLUMN IF NOT EXISTS codigo_cupom_aplicado VARCHAR(80) NULL;

ALTER TABLE flutz.pagamento
  DROP CONSTRAINT IF EXISTS fk_pagamento_empresa_cupom;
ALTER TABLE flutz.pagamento
  ADD CONSTRAINT fk_pagamento_empresa_cupom
    FOREIGN KEY (empresa_cupom_id) REFERENCES empresa_cupom (empresa_cupom_id)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- Slot ocupado também enquanto aguarda pagamento (profissional já atribuído).
CREATE OR REPLACE FUNCTION flutz.fn_agendamento_sem_conflito()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_ocupa boolean;
BEGIN
  SELECT s.codigo NOT IN ('CANCELADO', 'CANCELADO_CLIENTE', 'CANCELADO_CLINICA', 'RECUSADO', 'FALTOU', 'CONCLUIDO')
    INTO v_ocupa
  FROM flutz.agendamento_status s
  WHERE s.agendamento_status_id = NEW.agendamento_status_id;

  IF NOT COALESCE(v_ocupa, TRUE) THEN
    RETURN NEW;
  END IF;

  IF NEW.colaborador_id IS NOT NULL AND NEW.data_hora_fim IS NOT NULL THEN
    IF EXISTS (
      SELECT 1
      FROM flutz.agendamento a
      INNER JOIN flutz.agendamento_status s ON s.agendamento_status_id = a.agendamento_status_id
      WHERE a.colaborador_id = NEW.colaborador_id
        AND (TG_OP = 'INSERT' OR a.agendamento_id <> NEW.agendamento_id)
        AND s.codigo NOT IN ('CANCELADO', 'CANCELADO_CLIENTE', 'CANCELADO_CLINICA', 'RECUSADO', 'FALTOU', 'CONCLUIDO')
        AND a.data_hora_fim IS NOT NULL
        AND NEW.data_hora_inicio < a.data_hora_fim
        AND NEW.data_hora_fim > a.data_hora_inicio
    ) THEN
      RAISE EXCEPTION 'Colaborador ja possui agendamento neste horario.';
    END IF;
  END IF;

  IF NEW.colaborador_id IS NULL AND NEW.data_hora_fim IS NOT NULL THEN
    IF EXISTS (
      SELECT 1
      FROM flutz.agendamento a
      INNER JOIN flutz.agendamento_status s ON s.agendamento_status_id = a.agendamento_status_id
      WHERE a.empresa_id = NEW.empresa_id
        AND a.colaborador_id IS NULL
        AND (TG_OP = 'INSERT' OR a.agendamento_id <> NEW.agendamento_id)
        AND s.codigo IN ('CONFIRMADO', 'AGUARDANDO_CLIENTE', 'AGUARDANDO_PAGAMENTO')
        AND a.data_hora_fim IS NOT NULL
        AND NEW.data_hora_inicio < a.data_hora_fim
        AND NEW.data_hora_fim > a.data_hora_inicio
    ) THEN
      RAISE EXCEPTION 'Este horario ja esta confirmado na clinica.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;
