-- OAuth Mercado Pago por clínica (Connect) + state antifalsificação.
-- Preserva public_key/access_token manuais existentes (auth_mode = manual).

SET search_path TO flutz;

ALTER TABLE flutz.conta_pagamento
  ADD COLUMN IF NOT EXISTS refresh_token TEXT NULL,
  ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS provider_user_id VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS oauth_scope VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS auth_mode VARCHAR(20) NOT NULL DEFAULT 'manual';

ALTER TABLE flutz.conta_pagamento
  DROP CONSTRAINT IF EXISTS chk_conta_pagamento_auth_mode;
ALTER TABLE flutz.conta_pagamento
  ADD CONSTRAINT chk_conta_pagamento_auth_mode
    CHECK (auth_mode IN ('manual', 'oauth'));

COMMENT ON COLUMN flutz.conta_pagamento.refresh_token IS
  'Refresh token OAuth da clínica. Nunca expor ao frontend.';
COMMENT ON COLUMN flutz.conta_pagamento.token_expires_at IS
  'Expiração do access_token OAuth.';
COMMENT ON COLUMN flutz.conta_pagamento.provider_user_id IS
  'user_id do vendedor no Mercado Pago.';
COMMENT ON COLUMN flutz.conta_pagamento.auth_mode IS
  'manual = credenciais coladas (legado); oauth = Connect oficial.';

-- Contas já conectadas com token manual permanecem como manual.
UPDATE flutz.conta_pagamento
SET auth_mode = 'manual'
WHERE auth_mode IS NULL
   OR (access_token IS NOT NULL AND refresh_token IS NULL);

CREATE TABLE IF NOT EXISTS flutz.mercadopago_oauth_state (
  oauth_state_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  state_token VARCHAR(64) NOT NULL,
  empresa_id INT NOT NULL,
  ator_id INT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_mercadopago_oauth_state PRIMARY KEY (oauth_state_id),
  CONSTRAINT uk_mercadopago_oauth_state_token UNIQUE (state_token),
  CONSTRAINT fk_mp_oauth_state_empresa
    FOREIGN KEY (empresa_id) REFERENCES flutz.empresa (empresa_id)
);

CREATE INDEX IF NOT EXISTS ix_mp_oauth_state_empresa
  ON flutz.mercadopago_oauth_state (empresa_id);

CREATE INDEX IF NOT EXISTS ix_mp_oauth_state_expires
  ON flutz.mercadopago_oauth_state (expires_at);

COMMENT ON TABLE flutz.mercadopago_oauth_state IS
  'State CSRF/OAuth: vincula o callback à clínica e ao usuário que iniciou a conexão.';
