-- Agenda operacional da clínica: coordenadas, expediente, feriados, bloqueios,
-- vacinação na solicitação, status do processo e histórico de mudança.

SET search_path TO flutz;

ALTER TABLE flutz.empresa
  ADD COLUMN latitude DECIMAL(10,7) NULL,
  ADD COLUMN longitude DECIMAL(10,7) NULL,
  ADD COLUMN cancelamento_antecedencia_minutos INT NULL;

ALTER TABLE flutz.empresa
  ADD CONSTRAINT chk_empresa_coordenadas
    CHECK (
      (latitude IS NULL AND longitude IS NULL)
      OR (
        latitude IS NOT NULL AND longitude IS NOT NULL
        AND latitude BETWEEN -90 AND 90
        AND longitude BETWEEN -180 AND 180
      )
    );

ALTER TABLE flutz.empresa
  ADD CONSTRAINT chk_empresa_cancelamento_antecedencia
    CHECK (cancelamento_antecedencia_minutos IS NULL OR cancelamento_antecedencia_minutos >= 0);

COMMENT ON COLUMN flutz.empresa.latitude IS
  'Coordenada da clínica para distância. Sem isso o tutor vê cidade, não km.';

COMMENT ON COLUMN flutz.empresa.cancelamento_antecedencia_minutos IS
  'NULL = tutor pode cancelar enquanto o horário não passou. 120 = até 2 horas antes.';

ALTER TABLE flutz.cliente
  ADD COLUMN latitude DECIMAL(10,7) NULL,
  ADD COLUMN longitude DECIMAL(10,7) NULL,
  ADD COLUMN localizacao_atualizada_em TIMESTAMP NULL;

ALTER TABLE flutz.cliente
  ADD CONSTRAINT chk_cliente_coordenadas
    CHECK (
      (latitude IS NULL AND longitude IS NULL)
      OR (
        latitude IS NOT NULL AND longitude IS NOT NULL
        AND latitude BETWEEN -90 AND 90
        AND longitude BETWEEN -180 AND 180
      )
    );

COMMENT ON COLUMN flutz.cliente.latitude IS
  'Última localização informada pelo tutor no navegador, para distância até a clínica.';

CREATE TABLE flutz.empresa_expediente (
  empresa_expediente_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  dia_semana SMALLINT NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_expediente_id PRIMARY KEY (empresa_expediente_id),
  CONSTRAINT chk_empresa_expediente_dia CHECK (dia_semana BETWEEN 1 AND 7),
  CONSTRAINT chk_empresa_expediente_periodo CHECK (hora_fim > hora_inicio),
  CONSTRAINT fk_empresa_expediente_empresa
    FOREIGN KEY (empresa_id) REFERENCES empresa (empresa_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_expediente_status
    FOREIGN KEY (status_id) REFERENCES status (status_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_expediente_dia ON flutz.empresa_expediente (empresa_id, dia_semana);

CREATE TRIGGER trg_empresa_expediente_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_expediente
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_expediente IS
  'Grade semanal da clínica (1=segunda … 7=domingo). Várias faixas no mesmo dia (almoço).';

CREATE OR REPLACE FUNCTION flutz.fn_empresa_expediente_sem_sobrepor()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM flutz.empresa_expediente h
    WHERE h.empresa_id = NEW.empresa_id
      AND h.dia_semana = NEW.dia_semana
      AND (TG_OP = 'INSERT' OR h.empresa_expediente_id <> NEW.empresa_expediente_id)
      AND NEW.hora_inicio < h.hora_fim
      AND NEW.hora_fim > h.hora_inicio
  ) THEN
    RAISE EXCEPTION 'Faixa de expediente sobreposta neste dia.';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_empresa_expediente_sem_sobrepor
BEFORE INSERT OR UPDATE ON flutz.empresa_expediente
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_empresa_expediente_sem_sobrepor();

CREATE TABLE flutz.empresa_feriado (
  empresa_feriado_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  data DATE NOT NULL,
  nome VARCHAR(150) NOT NULL,
  atende BOOLEAN NOT NULL DEFAULT FALSE,
  hora_inicio TIME NULL,
  hora_fim TIME NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_feriado_id PRIMARY KEY (empresa_feriado_id),
  CONSTRAINT uk_empresa_feriado UNIQUE (empresa_id, data),
  CONSTRAINT chk_empresa_feriado_atende CHECK (atende IN (FALSE, TRUE)),
  CONSTRAINT chk_empresa_feriado_excepcional
    CHECK (
      (atende = FALSE AND hora_inicio IS NULL AND hora_fim IS NULL)
      OR (atende = TRUE AND hora_inicio IS NOT NULL AND hora_fim IS NOT NULL AND hora_fim > hora_inicio)
    ),
  CONSTRAINT fk_empresa_feriado_empresa
    FOREIGN KEY (empresa_id) REFERENCES empresa (empresa_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TRIGGER trg_empresa_feriado_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_feriado
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_feriado IS
  'Feriado da clínica. atende=TRUE abre expediente excepcional naquele dia.';

CREATE TABLE flutz.empresa_bloqueio (
  empresa_bloqueio_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  data_hora_inicio TIMESTAMP NOT NULL,
  data_hora_fim TIMESTAMP NOT NULL,
  motivo VARCHAR(255) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_bloqueio_id PRIMARY KEY (empresa_bloqueio_id),
  CONSTRAINT chk_empresa_bloqueio_periodo CHECK (data_hora_fim > data_hora_inicio),
  CONSTRAINT fk_empresa_bloqueio_empresa
    FOREIGN KEY (empresa_id) REFERENCES empresa (empresa_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_bloqueio_periodo ON flutz.empresa_bloqueio (empresa_id, data_hora_inicio);

CREATE TRIGGER trg_empresa_bloqueio_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_bloqueio
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_bloqueio IS
  'Bloqueio de período (manutenção, reunião). Pode ser o dia inteiro ou só uma faixa.';

CREATE TABLE flutz.empresa_agenda_nota (
  empresa_agenda_nota_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  data DATE NOT NULL,
  texto TEXT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_agenda_nota_id PRIMARY KEY (empresa_agenda_nota_id),
  CONSTRAINT uk_empresa_agenda_nota UNIQUE (empresa_id, data),
  CONSTRAINT fk_empresa_agenda_nota_empresa
    FOREIGN KEY (empresa_id) REFERENCES empresa (empresa_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TRIGGER trg_empresa_agenda_nota_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_agenda_nota
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_agenda_nota IS
  'Observação visível no dia da agenda da clínica.';

ALTER TABLE flutz.empresa_vacina
  ADD COLUMN visivel_agendamento BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN idade_minima_meses INT NULL,
  ADD COLUMN idade_maxima_meses INT NULL,
  ADD COLUMN intervalo_doses_dias INT NULL,
  ADD COLUMN observacoes TEXT NULL;

ALTER TABLE flutz.empresa_vacina
  ADD CONSTRAINT chk_empresa_vacina_agendamento
    CHECK (visivel_agendamento IN (FALSE, TRUE));

ALTER TABLE flutz.empresa_vacina
  ADD CONSTRAINT chk_empresa_vacina_idade
    CHECK (
      idade_minima_meses IS NULL OR idade_minima_meses >= 0
    );

ALTER TABLE flutz.empresa_vacina
  ADD CONSTRAINT chk_empresa_vacina_idade_max
    CHECK (
      idade_maxima_meses IS NULL
      OR (idade_maxima_meses >= 0 AND (idade_minima_meses IS NULL OR idade_maxima_meses >= idade_minima_meses))
    );

COMMENT ON COLUMN flutz.empresa_vacina.visivel_agendamento IS
  'Se FALSE, a vacina existe no catálogo da clínica mas o tutor não a solicita pela agenda.';

CREATE TABLE flutz.empresa_vacina_especie (
  empresa_vacina_especie_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_vacina_id INT NOT NULL,
  pet_especie_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_vacina_especie_id PRIMARY KEY (empresa_vacina_especie_id),
  CONSTRAINT uk_empresa_vacina_especie UNIQUE (empresa_vacina_id, pet_especie_id),
  CONSTRAINT fk_empresa_vacina_especie_vacina
    FOREIGN KEY (empresa_vacina_id) REFERENCES empresa_vacina (empresa_vacina_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_vacina_especie_especie
    FOREIGN KEY (pet_especie_id) REFERENCES pet_especie (pet_especie_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

COMMENT ON TABLE flutz.empresa_vacina_especie IS
  'Espécies em que a clínica oferece esta vacina. Sem linhas = todas as espécies que a clínica atende.';

INSERT INTO flutz.agendamento_status (codigo, descricao)
VALUES
    ('RECUSADO', 'Recusado'),
    ('CANCELADO_CLIENTE', 'Cancelado pelo tutor'),
    ('CANCELADO_CLINICA', 'Cancelado pela clínica'),
    ('AGUARDANDO_CLIENTE', 'Aguardando o tutor'),
    ('CONCLUIDO', 'Concluído')
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE flutz.agendamento
  ADD COLUMN tipo VARCHAR(20) NOT NULL DEFAULT 'ATENDIMENTO',
  ADD COLUMN empresa_vacina_id INT NULL,
  ADD COLUMN motivo_status TEXT NULL,
  ADD COLUMN data_hora_proposta_inicio TIMESTAMP NULL,
  ADD COLUMN data_hora_proposta_fim TIMESTAMP NULL;

ALTER TABLE flutz.agendamento
  ADD CONSTRAINT chk_agendamento_tipo
    CHECK (tipo IN ('ATENDIMENTO', 'VACINACAO'));

ALTER TABLE flutz.agendamento
  ADD CONSTRAINT chk_agendamento_tipo_alvo
    CHECK (
      (tipo = 'ATENDIMENTO' AND empresa_vacina_id IS NULL)
      OR (tipo = 'VACINACAO' AND empresa_vacina_id IS NOT NULL)
    );

ALTER TABLE flutz.agendamento
  ADD CONSTRAINT chk_agendamento_proposta
    CHECK (
      (data_hora_proposta_inicio IS NULL AND data_hora_proposta_fim IS NULL)
      OR (
        data_hora_proposta_inicio IS NOT NULL
        AND data_hora_proposta_fim IS NOT NULL
        AND data_hora_proposta_fim >= data_hora_proposta_inicio
      )
    );

ALTER TABLE flutz.agendamento
  ADD CONSTRAINT fk_agendamento_empresa_vacina
    FOREIGN KEY (empresa_vacina_id)
    REFERENCES empresa_vacina (empresa_vacina_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

CREATE INDEX idx_agendamento_vacina ON flutz.agendamento (empresa_vacina_id);

CREATE TABLE flutz.agendamento_evento (
  agendamento_evento_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  agendamento_id INT NOT NULL,
  empresa_id INT NOT NULL,
  ator_tipo VARCHAR(30) NOT NULL,
  ator_id INT NOT NULL,
  status_anterior_id INT NULL,
  status_novo_id INT NOT NULL,
  motivo TEXT NULL,
  data_evento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_agendamento_evento_id PRIMARY KEY (agendamento_evento_id),
  CONSTRAINT chk_agendamento_evento_ator
    CHECK (ator_tipo IN ('CLIENTE', 'COLABORADOR', 'ADMINISTRADOR_SISTEMA')),
  CONSTRAINT fk_agendamento_evento_agendamento
    FOREIGN KEY (agendamento_id) REFERENCES agendamento (agendamento_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_evento_empresa
    FOREIGN KEY (empresa_id) REFERENCES empresa (empresa_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_evento_status_anterior
    FOREIGN KEY (status_anterior_id) REFERENCES agendamento_status (agendamento_status_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_evento_status_novo
    FOREIGN KEY (status_novo_id) REFERENCES agendamento_status (agendamento_status_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_agendamento_evento_agendamento ON flutz.agendamento_evento (agendamento_id, data_evento);

COMMENT ON TABLE flutz.agendamento_evento IS
  'Histórico de mudança de status. Não apaga com cancelamento.';

CREATE OR REPLACE FUNCTION flutz.fn_agendamento_sem_conflito()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_ocupa boolean;
BEGIN
  SELECT s.codigo NOT IN ('CANCELADO', 'CANCELADO_CLIENTE', 'CANCELADO_CLINICA', 'RECUSADO', 'FALTOU', 'CONCLUIDO')
    INTO v_ocupa
  FROM flutz.agendamento_status s
  WHERE s.agendamento_status_id = NEW.agendamento_status_id;

  IF NOT COALESCE(v_ocupa, TRUE) THEN
    RETURN NEW;
  END IF;

  IF NEW.colaborador_id IS NOT NULL AND NEW.data_hora_fim IS NOT NULL THEN
    IF EXISTS (
      SELECT 1
      FROM flutz.agendamento a
      INNER JOIN flutz.agendamento_status s ON s.agendamento_status_id = a.agendamento_status_id
      WHERE a.colaborador_id = NEW.colaborador_id
        AND (TG_OP = 'INSERT' OR a.agendamento_id <> NEW.agendamento_id)
        AND s.codigo NOT IN ('CANCELADO', 'CANCELADO_CLIENTE', 'CANCELADO_CLINICA', 'RECUSADO', 'FALTOU', 'CONCLUIDO')
        AND a.data_hora_fim IS NOT NULL
        AND NEW.data_hora_inicio < a.data_hora_fim
        AND NEW.data_hora_fim > a.data_hora_inicio
    ) THEN
      RAISE EXCEPTION 'Colaborador ja possui agendamento neste horario.';
    END IF;
  END IF;

  IF NEW.colaborador_id IS NULL AND NEW.data_hora_fim IS NOT NULL THEN
    IF EXISTS (
      SELECT 1
      FROM flutz.agendamento a
      INNER JOIN flutz.agendamento_status s ON s.agendamento_status_id = a.agendamento_status_id
      WHERE a.empresa_id = NEW.empresa_id
        AND a.colaborador_id IS NULL
        AND (TG_OP = 'INSERT' OR a.agendamento_id <> NEW.agendamento_id)
        AND s.codigo IN ('CONFIRMADO', 'AGUARDANDO_CLIENTE')
        AND a.data_hora_fim IS NOT NULL
        AND NEW.data_hora_inicio < a.data_hora_fim
        AND NEW.data_hora_fim > a.data_hora_inicio
    ) THEN
      RAISE EXCEPTION 'Este horario ja esta confirmado na clinica.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;
