ALTER TABLE flutz.colaborador
  ADD COLUMN IF NOT EXISTS permitir_notificacoes BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE flutz.colaborador
  DROP CONSTRAINT IF EXISTS chk_colaborador_permitir_notificacoes;

ALTER TABLE flutz.colaborador
  ADD CONSTRAINT chk_colaborador_permitir_notificacoes
    CHECK (permitir_notificacoes IN (FALSE, TRUE));

COMMENT ON COLUMN flutz.colaborador.permitir_notificacoes IS
  'Se falso, a clínica e a plataforma não enviam avisos a este colaborador.';

CREATE TABLE IF NOT EXISTS flutz.ticket_suporte (
  ticket_suporte_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  tipo_solicitante VARCHAR(32) NOT NULL,
  ator_id INTEGER NOT NULL,
  empresa_id INTEGER NULL,
  nome_solicitante VARCHAR(150) NOT NULL,
  email_contato VARCHAR(255) NOT NULL,
  motivo VARCHAR(180) NOT NULL,
  mensagem VARCHAR(4000) NOT NULL,
  status_ticket VARCHAR(20) NOT NULL DEFAULT 'ABERTO',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_ticket_suporte_id PRIMARY KEY (ticket_suporte_id),
  CONSTRAINT chk_ticket_suporte_tipo
    CHECK (tipo_solicitante IN ('CLIENTE', 'COLABORADOR')),
  CONSTRAINT chk_ticket_suporte_status
    CHECK (status_ticket IN ('ABERTO', 'EM_ANDAMENTO', 'RESOLVIDO')),
  CONSTRAINT fk_ticket_suporte_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ticket_suporte_status_data
  ON flutz.ticket_suporte (status_ticket, criado_em DESC);

COMMENT ON TABLE flutz.ticket_suporte IS
  'Pedidos de suporte enviados pelo tutor ou pela clínica à administração do Flutz.';
