-- =============================================================================
-- Flutz — Modelo físico de referência (SaaS para clínicas veterinárias)
-- PostgreSQL 16+
--
-- Conversão do script MySQL 8 / InnoDB. Regras de negócio, PKs, FKs,
-- cardinalidades e CHECKs foram preservados. Apenas a sintaxe do SGBD mudou.
--
-- Fonte histórica (Workbench): database/mysql/modelo-fisico-saas-veterinario.sql
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS flutz;
SET search_path TO flutz;

CREATE OR REPLACE FUNCTION flutz.set_ultima_atualizacao()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.ultima_atualizacao = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

-- =============================================================================
-- Flutz — Modelo físico de referência (SaaS para clínicas veterinárias)
--
-- Este script representa o NOVO modelo físico consolidado.
-- Não contém dados fictícios.
-- =============================================================================
-- -----------------------------------------------------------------------------
-- 1. Catálogos globais (sem tenant)
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.status (
  status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_status_id PRIMARY KEY (status_id),
  CONSTRAINT uk_status_descricao UNIQUE (descricao)
);

COMMENT ON TABLE flutz.status IS
  'Catálogo de status cadastral (ativo, inativo, pendente, bloqueado, inadimplente).';

CREATE TABLE flutz.imagem_posicao (
  imagem_posicao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  posicao VARCHAR(45) NOT NULL,
  CONSTRAINT pk_imagem_posicao_id PRIMARY KEY (imagem_posicao_id),
  CONSTRAINT uk_imagem_posicao_posicao UNIQUE (posicao)
);

COMMENT ON TABLE flutz.imagem_posicao IS
  'Posição da imagem de fundo da hero (centro, topo, etc.).';

CREATE TABLE flutz.tipo_redesocial (
  tipo_redesocial_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  icone_url VARCHAR(500) NULL,
  CONSTRAINT pk_tipo_redesocial_id PRIMARY KEY (tipo_redesocial_id),
  CONSTRAINT uk_tipo_redesocial_descricao UNIQUE (descricao)
);

COMMENT ON TABLE flutz.tipo_redesocial IS
  'Catálogo global de redes sociais (Instagram, Facebook, TikTok, YouTube, etc.).';

CREATE TABLE flutz.tipo_servico (
  tipo_servico_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  tipo_servico VARCHAR(80) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_tipo_servico_id PRIMARY KEY (tipo_servico_id),
  CONSTRAINT uk_tipo_servico_nome UNIQUE (tipo_servico)
);

COMMENT ON TABLE flutz.tipo_servico IS
  'Catálogo global de tipos de serviço. A oferta da clínica fica em empresa_servico.';

CREATE TABLE flutz.especialidade (
  especialidade_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_especialidade_id PRIMARY KEY (especialidade_id),
  CONSTRAINT uk_especialidade_descricao UNIQUE (descricao)
);

COMMENT ON TABLE flutz.especialidade IS
  'Catálogo global de especialidades veterinárias.';

CREATE TABLE flutz.role (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_role_id PRIMARY KEY (role_id),
  CONSTRAINT uk_role_descricao UNIQUE (descricao)
);

COMMENT ON TABLE flutz.role IS
  'Autorização do colaborador (administrador, veterinário, recepção, etc.). Cliente não usa role.';

CREATE TABLE flutz.pet_especie (
  pet_especie_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_pet_especie_id PRIMARY KEY (pet_especie_id),
  CONSTRAINT uk_pet_especie_descricao UNIQUE (descricao)
);

CREATE TRIGGER trg_pet_especie_ultima_atualizacao
BEFORE UPDATE ON flutz.pet_especie
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.pet_especie IS
  'Catálogo global de espécies.';

CREATE TABLE flutz.pet_raca (
  pet_raca_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  pet_especie_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_pet_raca_id PRIMARY KEY (pet_raca_id),

  CONSTRAINT uk_pet_raca_especie_descricao UNIQUE (pet_especie_id, descricao),
  CONSTRAINT fk_pet_raca_especie
    FOREIGN KEY (pet_especie_id)
    REFERENCES pet_especie (pet_especie_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_pet_raca_especie ON flutz.pet_raca (pet_especie_id);

CREATE TRIGGER trg_pet_raca_ultima_atualizacao
BEFORE UPDATE ON flutz.pet_raca
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.pet_raca IS
  'Catálogo global de raças, sempre vinculadas a uma espécie.';

CREATE TABLE flutz.doenca (
  doenca_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome_doenca VARCHAR(150) NOT NULL,
  nome_cientifico VARCHAR(150) NULL,
  descricao TEXT NULL,
  agente_causador VARCHAR(150) NULL,
  tipo VARCHAR(80) NULL,
  forma_transmissao TEXT NULL,
  periodo_incubacao VARCHAR(80) NULL,
  sintomas TEXT NULL,
  gravidade VARCHAR(80) NULL,
  tratamento TEXT NULL,
  prevencao TEXT NULL,
  contagiosa BOOLEAN NOT NULL DEFAULT FALSE,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_doenca_id PRIMARY KEY (doenca_id),
  CONSTRAINT uk_doenca_nome UNIQUE (nome_doenca),
  CONSTRAINT chk_doenca_contagiosa
    CHECK (contagiosa IN (FALSE, TRUE))
);

CREATE TRIGGER trg_doenca_ultima_atualizacao
BEFORE UPDATE ON flutz.doenca
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.doenca IS
  'Catálogo global de doenças.';

CREATE TABLE flutz.vacina (
  vacina_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome_vacina VARCHAR(150) NOT NULL,
  descricao TEXT NULL,
  fabricante VARCHAR(150) NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_vacina_id PRIMARY KEY (vacina_id),
  CONSTRAINT uk_vacina_nome UNIQUE (nome_vacina)
);

CREATE TRIGGER trg_vacina_ultima_atualizacao
BEFORE UPDATE ON flutz.vacina
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.vacina IS
  'Catálogo global de vacinas.';

CREATE TABLE flutz.vacina_doenca (
  vacina_doenca_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  vacina_id INT NOT NULL,
  doenca_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_vacina_doenca_id PRIMARY KEY (vacina_doenca_id),
  CONSTRAINT uk_vacina_doenca UNIQUE (vacina_id, doenca_id),

  CONSTRAINT fk_vacina_doenca_vacina
    FOREIGN KEY (vacina_id)
    REFERENCES vacina (vacina_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_vacina_doenca_doenca
    FOREIGN KEY (doenca_id)
    REFERENCES doenca (doenca_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_vacina_doenca_doenca ON flutz.vacina_doenca (doenca_id);

COMMENT ON TABLE flutz.vacina_doenca IS
  'N:N — doenças prevenidas por cada vacina.';

CREATE TABLE flutz.atendimento_status (
  atendimento_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_atendimento_status_id PRIMARY KEY (atendimento_status_id),
  CONSTRAINT uk_atendimento_status_descricao UNIQUE (descricao)
);

COMMENT ON TABLE flutz.atendimento_status IS
  'Status operacional do atendimento clínico.';

CREATE TABLE flutz.agendamento_status (
  agendamento_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  codigo VARCHAR(30) NOT NULL,
  descricao VARCHAR(80) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_agendamento_status_id PRIMARY KEY (agendamento_status_id),
  CONSTRAINT uk_agendamento_status_codigo UNIQUE (codigo),
  CONSTRAINT uk_agendamento_status_descricao UNIQUE (descricao)
);

COMMENT ON TABLE flutz.agendamento_status IS
  'Status operacional do agendamento. CANCELADO e FALTOU não bloqueiam horário.';

COMMENT ON COLUMN flutz.agendamento_status.codigo IS
  'Ex.: SOLICITADO, CONFIRMADO, CANCELADO, FALTOU.';

CREATE TABLE flutz.chat_motivo (
  chat_motivo_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(80) NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_chat_motivo_id PRIMARY KEY (chat_motivo_id),
  CONSTRAINT uk_chat_motivo_descricao UNIQUE (descricao),

  CONSTRAINT fk_chat_motivo_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_chat_motivo_status ON flutz.chat_motivo (status_id);

COMMENT ON TABLE flutz.chat_motivo IS
  'Catálogo de motivos de abertura de chat. Não referencia um chat específico.';

CREATE TABLE flutz.plano (
  plano_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  codigo VARCHAR(30) NOT NULL,
  nome VARCHAR(80) NOT NULL,
  descricao TEXT NULL,
  valor_mensal DECIMAL(10,2) NOT NULL,
  moeda CHAR(3) NOT NULL DEFAULT 'BRL',
  limite_colaboradores INT NULL,
  limite_clientes INT NULL,
  permite_pagina_publica BOOLEAN NOT NULL DEFAULT TRUE,
  permite_doacoes BOOLEAN NOT NULL DEFAULT FALSE,
  permite_pagamentos BOOLEAN NOT NULL DEFAULT FALSE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_plano_id PRIMARY KEY (plano_id),
  CONSTRAINT uk_plano_codigo UNIQUE (codigo),
  CONSTRAINT chk_plano_valor
    CHECK (valor_mensal >= 0),
  CONSTRAINT chk_plano_flags
    CHECK (
      permite_pagina_publica IN (FALSE, TRUE)
      AND permite_doacoes IN (FALSE, TRUE)
      AND permite_pagamentos IN (FALSE, TRUE)
      AND ativo IN (FALSE, TRUE)
    )
);

CREATE TRIGGER trg_plano_ultima_atualizacao
BEFORE UPDATE ON flutz.plano
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.plano IS
  'Catálogo de planos do SaaS (BASICO, PROFISSIONAL, PREMIUM).';

COMMENT ON COLUMN flutz.plano.limite_colaboradores IS
  'NULL = ilimitado';

COMMENT ON COLUMN flutz.plano.limite_clientes IS
  'NULL = ilimitado';

CREATE TABLE flutz.administrador_sistema (
  administrador_sistema_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  status_id INT NOT NULL,
  anonimizado_em TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_administrador_sistema_id PRIMARY KEY (administrador_sistema_id),
  CONSTRAINT uk_administrador_sistema_email UNIQUE (email),

  CONSTRAINT fk_administrador_sistema_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_administrador_sistema_status ON flutz.administrador_sistema (status_id);

CREATE TRIGGER trg_administrador_sistema_ultima_atualizacao
BEFORE UPDATE ON flutz.administrador_sistema
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.administrador_sistema IS
  'Administrador de todo o SaaS. Sem empresa_id. Não usa role de colaborador.';

COMMENT ON COLUMN flutz.administrador_sistema.senha_hash IS
  'Hash da senha. Login: e-mail + senha.';

COMMENT ON COLUMN flutz.administrador_sistema.anonimizado_em IS
  'Preenchido quando o titular é anonimizado (LGPD).';

CREATE TABLE flutz.token (
  token_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  codigo_token VARCHAR(80) NOT NULL,
  percentual_desconto DECIMAL(5,2) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_expiracao TIMESTAMP NOT NULL,
  status_id INT NOT NULL,
  administrador_sistema_id INT NOT NULL,
  usos_maximos_por_empresa INT NULL,
  CONSTRAINT pk_token_id PRIMARY KEY (token_id),
  CONSTRAINT uk_token_codigo UNIQUE (codigo_token),



  CONSTRAINT chk_token_percentual
    CHECK (percentual_desconto >= 0 AND percentual_desconto <= 100),
  CONSTRAINT chk_token_expiracao
    CHECK (data_expiracao > data_criacao),
  CONSTRAINT chk_token_usos_maximos
    CHECK (usos_maximos_por_empresa IS NULL OR usos_maximos_por_empresa >= 1),
  CONSTRAINT fk_token_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_token_administrador_sistema
    FOREIGN KEY (administrador_sistema_id)
    REFERENCES administrador_sistema (administrador_sistema_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_token_status ON flutz.token (status_id);

CREATE INDEX idx_token_expiracao ON flutz.token (data_expiracao);

CREATE INDEX idx_token_administrador ON flutz.token (administrador_sistema_id);

COMMENT ON TABLE flutz.token IS
  'Cupom de desconto da plataforma (mensalidade). Só administrador_sistema cria.';

COMMENT ON COLUMN flutz.token.percentual_desconto IS
  'Percentual 0–100. DECIMAL evita erro de FLOAT em cálculo de desconto.';

COMMENT ON COLUMN flutz.token.administrador_sistema_id IS
  'Quem criou o cupom.';

COMMENT ON COLUMN flutz.token.usos_maximos_por_empresa IS
  'NULL = ilimitado na clínica. 1 = uma fatura (ex.: primeira mensalidade).';

-- -----------------------------------------------------------------------------
-- 2. Tenant
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.empresa (
  empresa_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome_empresa VARCHAR(150) NOT NULL,
  razao_social VARCHAR(150) NULL,
  cnpj VARCHAR(18) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(20) NULL,
  logo_url VARCHAR(500) NULL,
  identificador_url VARCHAR(80) NOT NULL,
  descricao_empresa TEXT NULL,
  logradouro VARCHAR(150) NULL,
  numero VARCHAR(20) NULL,
  complemento VARCHAR(80) NULL,
  bairro VARCHAR(80) NULL,
  cidade VARCHAR(80) NULL,
  uf CHAR(2) NULL,
  cep VARCHAR(9) NULL,
  localizacao_googlemaps_url TEXT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_id PRIMARY KEY (empresa_id),
  CONSTRAINT uk_empresa_cnpj UNIQUE (cnpj),
  CONSTRAINT uk_empresa_identificador_url UNIQUE (identificador_url),


  CONSTRAINT fk_empresa_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_status ON flutz.empresa (status_id);

CREATE INDEX idx_empresa_cidade_uf ON flutz.empresa (uf, cidade);

CREATE TRIGGER trg_empresa_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa IS
  'Clínica/tenant. Endereço e texto institucional ficam aqui (não duplicar na página).';

COMMENT ON COLUMN flutz.empresa.descricao_empresa IS
  'Conteúdo da seção Sobre a clínica';

-- -----------------------------------------------------------------------------
-- 3. Página pública — configuração de seções e conteúdo próprio
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.pagina_secao (
  pagina_secao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  tipo_secao VARCHAR(30) NOT NULL,
  ordem INT NOT NULL,
  visivel BOOLEAN NOT NULL DEFAULT TRUE,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_pagina_secao_id PRIMARY KEY (pagina_secao_id),
  CONSTRAINT uk_pagina_secao_empresa_tipo UNIQUE (empresa_id, tipo_secao),

  CONSTRAINT chk_pagina_secao_tipo
    CHECK (tipo_secao IN (
      'HERO',
      'SOBRE',
      'SERVICOS',
      'ESPECIALIDADE',
      'EQUIPE',
      'AVALIACOES',
      'GALERIA',
      'LOCALIZACAO',
      'CONTATO',
      'DOACOES'
    )),
  CONSTRAINT chk_pagina_secao_ordem
    CHECK (ordem >= 1),
  CONSTRAINT chk_pagina_secao_visivel
    CHECK (visivel IN (FALSE, TRUE)),
  CONSTRAINT fk_pagina_secao_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_pagina_secao_empresa_ordem ON flutz.pagina_secao (empresa_id, ordem);

CREATE TRIGGER trg_pagina_secao_ultima_atualizacao
BEFORE UPDATE ON flutz.pagina_secao
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.pagina_secao IS
  'Ordem e visibilidade das seções da página pública. Uma linha por tipo e empresa.';

CREATE TABLE flutz.hero_section (
  hero_section_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  titulo VARCHAR(150) NOT NULL,
  subtitulo VARCHAR(255) NULL,
  texto_resumo TEXT NULL,
  imagem_fundo_url VARCHAR(500) NULL,
  imagem_posicao_id INT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_hero_section_id PRIMARY KEY (hero_section_id),
  CONSTRAINT uk_hero_section_empresa UNIQUE (empresa_id),

  CONSTRAINT fk_hero_section_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_hero_section_imagem_posicao
    FOREIGN KEY (imagem_posicao_id)
    REFERENCES imagem_posicao (imagem_posicao_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX idx_hero_section_posicao ON flutz.hero_section (imagem_posicao_id);

CREATE TRIGGER trg_hero_section_ultima_atualizacao
BEFORE UPDATE ON flutz.hero_section
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.hero_section IS
  'Conteúdo da Hero. Cardinalidade EMPRESA 1:1 HERO_SECTION.';

CREATE TABLE flutz.hero_section_topico (
  hero_section_topico_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  hero_section_id INT NOT NULL,
  titulo_topico VARCHAR(150) NOT NULL,
  texto_topico TEXT NULL,
  icone_url VARCHAR(500) NULL,
  ordem INT NOT NULL DEFAULT 1,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_hero_section_topico_id PRIMARY KEY (hero_section_topico_id),

  CONSTRAINT chk_hero_topico_ordem
    CHECK (ordem >= 1),
  CONSTRAINT fk_hero_section_topico_hero
    FOREIGN KEY (hero_section_id)
    REFERENCES hero_section (hero_section_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX idx_hero_topico_hero_ordem ON flutz.hero_section_topico (hero_section_id, ordem);

CREATE TRIGGER trg_hero_section_topico_ultima_atualizacao
BEFORE UPDATE ON flutz.hero_section_topico
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.hero_section_topico IS
  'Tópicos/destaques da Hero. Tenant indireto via hero_section.empresa_id.';

CREATE TABLE flutz.avaliacao_cliente (
  avaliacao_cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  cliente_id INT NULL,
  pet_id INT NULL,
  nome_cliente VARCHAR(150) NOT NULL,
  nome_pet VARCHAR(80) NULL,
  texto TEXT NOT NULL,
  nota DECIMAL(2,1) NOT NULL,
  imagem_url VARCHAR(500) NULL,
  visivel BOOLEAN NOT NULL DEFAULT FALSE,
  autorizado_publicacao BOOLEAN NOT NULL DEFAULT FALSE,
  data_autorizacao TIMESTAMP NULL,
  data_avaliacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_avaliacao_cliente_id PRIMARY KEY (avaliacao_cliente_id),




  CONSTRAINT chk_avaliacao_nota
    CHECK (nota >= 0 AND nota <= 5),
  CONSTRAINT chk_avaliacao_visivel
    CHECK (visivel IN (FALSE, TRUE)),
  CONSTRAINT chk_avaliacao_autorizado
    CHECK (autorizado_publicacao IN (FALSE, TRUE)),
  CONSTRAINT chk_avaliacao_publicacao
    CHECK (
      (autorizado_publicacao = FALSE AND visivel = FALSE)
      OR (
        autorizado_publicacao = TRUE
        AND data_autorizacao IS NOT NULL
      )
    ),
  CONSTRAINT fk_avaliacao_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_avaliacao_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_avaliacao_empresa_visivel ON flutz.avaliacao_cliente (empresa_id, visivel, data_avaliacao);

CREATE INDEX idx_avaliacao_cliente ON flutz.avaliacao_cliente (cliente_id);

CREATE INDEX idx_avaliacao_pet ON flutz.avaliacao_cliente (pet_id);

CREATE INDEX idx_avaliacao_status ON flutz.avaliacao_cliente (status_id);

CREATE TRIGGER trg_avaliacao_cliente_ultima_atualizacao
BEFORE UPDATE ON flutz.avaliacao_cliente
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.avaliacao_cliente IS
  'Depoimentos da página. cliente_id/pet_id opcionais (depoimento pode ser apenas textual).';

COMMENT ON COLUMN flutz.avaliacao_cliente.autorizado_publicacao IS
  'Tutor autorizou publicar nome/texto/foto na página.';

CREATE TABLE flutz.galeria_imagem (
  galeria_imagem_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  imagem_url VARCHAR(500) NOT NULL,
  texto_alternativo VARCHAR(255) NULL,
  ordem INT NOT NULL DEFAULT 1,
  visivel BOOLEAN NOT NULL DEFAULT TRUE,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_galeria_imagem_id PRIMARY KEY (galeria_imagem_id),


  CONSTRAINT chk_galeria_ordem
    CHECK (ordem >= 1),
  CONSTRAINT chk_galeria_visivel
    CHECK (visivel IN (FALSE, TRUE)),
  CONSTRAINT fk_galeria_imagem_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_galeria_imagem_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_galeria_empresa_ordem ON flutz.galeria_imagem (empresa_id, ordem);

CREATE INDEX idx_galeria_status ON flutz.galeria_imagem (status_id);

CREATE TRIGGER trg_galeria_imagem_ultima_atualizacao
BEFORE UPDATE ON flutz.galeria_imagem
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.galeria_imagem IS
  'Imagens da galeria pública da clínica. Substitui galeria_carrouseul.';

CREATE TABLE flutz.rede_social (
  rede_social_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  tipo_redesocial_id INT NOT NULL,
  nome_exibicao VARCHAR(80) NULL,
  url VARCHAR(500) NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_rede_social_id PRIMARY KEY (rede_social_id),
  CONSTRAINT uk_rede_social_empresa_tipo UNIQUE (empresa_id, tipo_redesocial_id),


  CONSTRAINT fk_rede_social_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_rede_social_tipo
    FOREIGN KEY (tipo_redesocial_id)
    REFERENCES tipo_redesocial (tipo_redesocial_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_rede_social_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_rede_social_tipo ON flutz.rede_social (tipo_redesocial_id);

CREATE INDEX idx_rede_social_status ON flutz.rede_social (status_id);

CREATE TRIGGER trg_rede_social_ultima_atualizacao
BEFORE UPDATE ON flutz.rede_social
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.rede_social IS
  'URLs de redes sociais da empresa. Uma linha por tipo e empresa.';

-- -----------------------------------------------------------------------------
-- 4. Pessoas: cliente (global) e colaborador (por empresa)
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.cliente (
  cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome_cliente VARCHAR(150) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  telefone VARCHAR(20) NULL,
  email VARCHAR(255) NULL,
  permitir_notificacoes BOOLEAN NOT NULL DEFAULT TRUE,
  status_id INT NOT NULL,
  anonimizado_em TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cliente_id PRIMARY KEY (cliente_id),
  CONSTRAINT uk_cliente_cpf UNIQUE (cpf),


  CONSTRAINT chk_cliente_permitir_notificacoes
    CHECK (permitir_notificacoes IN (FALSE, TRUE)),
  CONSTRAINT fk_cliente_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_cliente_status ON flutz.cliente (status_id);

CREATE INDEX idx_cliente_email ON flutz.cliente (email);

CREATE TRIGGER trg_cliente_ultima_atualizacao
BEFORE UPDATE ON flutz.cliente
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON COLUMN flutz.cliente.senha_hash IS
  'Hash da senha (nunca texto puro). Login: CPF + senha.';

COMMENT ON COLUMN flutz.cliente.permitir_notificacoes IS
  'Se 0, nenhum canal pode notificar este tutor.';

COMMENT ON COLUMN flutz.cliente.anonimizado_em IS
  'Preenchido quando o titular é anonimizado (LGPD). Login deixa de ser possível.';

CREATE TABLE flutz.empresa_cliente (
  empresa_cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  cliente_id INT NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_cliente_id PRIMARY KEY (empresa_cliente_id),
  CONSTRAINT uk_empresa_cliente UNIQUE (empresa_id, cliente_id),


  CONSTRAINT fk_empresa_cliente_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_cliente_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_cliente_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_cliente_cliente ON flutz.empresa_cliente (cliente_id);

CREATE INDEX idx_empresa_cliente_status ON flutz.empresa_cliente (status_id);

CREATE TRIGGER trg_empresa_cliente_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_cliente
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_cliente IS
  'N:N — um tutor pode ser cliente de várias clínicas.';

CREATE TABLE flutz.colaborador (
  colaborador_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  nome_colaborador VARCHAR(150) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  telefone VARCHAR(20) NULL,
  cargo VARCHAR(80) NULL,
  funcao TEXT NULL,
  descricao TEXT NULL,
  imagem_url VARCHAR(500) NULL,
  exibir_pagina BOOLEAN NOT NULL DEFAULT FALSE,
  data_autorizacao_pagina TIMESTAMP NULL,
  ordem_pagina INT NULL,
  status_id INT NOT NULL,
  anonimizado_em TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_colaborador_id PRIMARY KEY (colaborador_id),
  CONSTRAINT uk_colaborador_empresa_cpf UNIQUE (empresa_id, cpf),
  CONSTRAINT uk_colaborador_email UNIQUE (email),


  CONSTRAINT chk_colaborador_exibir_pagina
    CHECK (exibir_pagina IN (FALSE, TRUE)),
  CONSTRAINT chk_colaborador_autorizacao_pagina
    CHECK (
      exibir_pagina = FALSE
      OR (exibir_pagina = TRUE AND data_autorizacao_pagina IS NOT NULL)
    ),
  CONSTRAINT fk_colaborador_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_colaborador_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_colaborador_empresa_pagina ON flutz.colaborador (empresa_id, exibir_pagina, ordem_pagina);

CREATE INDEX idx_colaborador_status ON flutz.colaborador (status_id);

CREATE TRIGGER trg_colaborador_ultima_atualizacao
BEFORE UPDATE ON flutz.colaborador
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.colaborador IS
  'Equipe da clínica. Login com e-mail + senha. Autorização via colaborador_role. exibir_pagina = equipe pública.';

COMMENT ON COLUMN flutz.colaborador.email IS
  'Identificador de login do colaborador.';

COMMENT ON COLUMN flutz.colaborador.senha_hash IS
  'Hash da senha (nunca texto puro). Login: e-mail + senha.';

COMMENT ON COLUMN flutz.colaborador.data_autorizacao_pagina IS
  'Quando o colaborador autorizou aparecer na página pública.';

COMMENT ON COLUMN flutz.colaborador.anonimizado_em IS
  'Preenchido quando o titular é anonimizado (LGPD).';

CREATE TABLE flutz.colaborador_horario (
  colaborador_horario_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  colaborador_id INT NOT NULL,
  dia_semana SMALLINT NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_colaborador_horario_id PRIMARY KEY (colaborador_horario_id),


  CONSTRAINT chk_colaborador_horario_dia
    CHECK (dia_semana BETWEEN 1 AND 7),
  CONSTRAINT chk_colaborador_horario_periodo
    CHECK (hora_fim > hora_inicio),
  CONSTRAINT fk_colaborador_horario_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_colaborador_horario_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_colaborador_horario_dia ON flutz.colaborador_horario (colaborador_id, dia_semana);

CREATE INDEX idx_colaborador_horario_status ON flutz.colaborador_horario (status_id);

CREATE TRIGGER trg_colaborador_horario_ultima_atualizacao
BEFORE UPDATE ON flutz.colaborador_horario
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.colaborador_horario IS
  'Grade semanal em que o profissional atende. Slots livres = grade menos agendamentos.';

COMMENT ON COLUMN flutz.colaborador_horario.dia_semana IS
  '1=segunda ... 7=domingo (ISO).';

CREATE TABLE flutz.colaborador_role (
  colaborador_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  colaborador_id INT NOT NULL,
  role_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_colaborador_role_id PRIMARY KEY (colaborador_role_id),
  CONSTRAINT uk_colaborador_role UNIQUE (colaborador_id, role_id),

  CONSTRAINT fk_colaborador_role_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_colaborador_role_role
    FOREIGN KEY (role_id)
    REFERENCES role (role_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_colaborador_role_role ON flutz.colaborador_role (role_id);

COMMENT ON TABLE flutz.colaborador_role IS
  'N:N — papéis de um colaborador.';

-- -----------------------------------------------------------------------------
-- 5. Oferta da clínica: especialidades, serviços, catálogos habilitados
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.empresa_especialidade (
  empresa_especialidade_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  especialidade_id INT NOT NULL,
  descricao TEXT NULL,
  imagem_url VARCHAR(500) NULL,
  ordem INT NOT NULL DEFAULT 1,
  visivel_pagina BOOLEAN NOT NULL DEFAULT TRUE,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_especialidade_id PRIMARY KEY (empresa_especialidade_id),
  CONSTRAINT uk_empresa_especialidade UNIQUE (empresa_id, especialidade_id),



  CONSTRAINT chk_empresa_especialidade_visivel
    CHECK (visivel_pagina IN (FALSE, TRUE)),
  CONSTRAINT fk_empresa_especialidade_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_especialidade_especialidade
    FOREIGN KEY (especialidade_id)
    REFERENCES especialidade (especialidade_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_especialidade_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_especialidade_catalogo ON flutz.empresa_especialidade (especialidade_id);

CREATE INDEX idx_empresa_especialidade_pagina ON flutz.empresa_especialidade (empresa_id, visivel_pagina, ordem);

CREATE INDEX idx_empresa_especialidade_status ON flutz.empresa_especialidade (status_id);

CREATE TRIGGER trg_empresa_especialidade_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_especialidade
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_especialidade IS
  'N:N — especialidades oferecidas pela clínica, com texto/imagem próprios.';

CREATE TABLE flutz.colaborador_especialidade (
  colaborador_especialidade_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  colaborador_id INT NOT NULL,
  empresa_especialidade_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_colaborador_especialidade_id PRIMARY KEY (colaborador_especialidade_id),
  CONSTRAINT uk_colaborador_especialidade UNIQUE (colaborador_id, empresa_especialidade_id),

  CONSTRAINT fk_colaborador_especialidade_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_colaborador_especialidade_empresa_esp
    FOREIGN KEY (empresa_especialidade_id)
    REFERENCES empresa_especialidade (empresa_especialidade_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_colaborador_especialidade_esp ON flutz.colaborador_especialidade (empresa_especialidade_id);

COMMENT ON TABLE flutz.colaborador_especialidade IS
  'N:N — colaborador só se associa a especialidades já oferecidas pela própria empresa.';

CREATE TABLE flutz.empresa_servico (
  empresa_servico_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  tipo_servico_id INT NOT NULL,
  nome_exibicao VARCHAR(150) NULL,
  descricao TEXT NULL,
  imagem_url VARCHAR(500) NULL,
  preco DECIMAL(10,2) NULL,
  duracao_minutos INT NULL,
  ordem INT NOT NULL DEFAULT 1,
  visivel_pagina BOOLEAN NOT NULL DEFAULT TRUE,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_servico_id PRIMARY KEY (empresa_servico_id),
  CONSTRAINT uk_empresa_servico UNIQUE (empresa_id, tipo_servico_id),



  CONSTRAINT chk_empresa_servico_preco
    CHECK (preco IS NULL OR preco >= 0),
  CONSTRAINT chk_empresa_servico_duracao
    CHECK (duracao_minutos IS NULL OR duracao_minutos > 0),
  CONSTRAINT chk_empresa_servico_visivel
    CHECK (visivel_pagina IN (FALSE, TRUE)),
  CONSTRAINT fk_empresa_servico_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_servico_tipo
    FOREIGN KEY (tipo_servico_id)
    REFERENCES tipo_servico (tipo_servico_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_servico_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_servico_tipo ON flutz.empresa_servico (tipo_servico_id);

CREATE INDEX idx_empresa_servico_pagina ON flutz.empresa_servico (empresa_id, visivel_pagina, ordem);

CREATE INDEX idx_empresa_servico_status ON flutz.empresa_servico (status_id);

CREATE TRIGGER trg_empresa_servico_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_servico
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_servico IS
  'Oferta N:N: tipo global + customização/preço/duração por empresa.';

CREATE TABLE flutz.empresa_vacina (
  empresa_vacina_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  vacina_id INT NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_vacina_id PRIMARY KEY (empresa_vacina_id),
  CONSTRAINT uk_empresa_vacina UNIQUE (empresa_id, vacina_id),


  CONSTRAINT fk_empresa_vacina_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_vacina_vacina
    FOREIGN KEY (vacina_id)
    REFERENCES vacina (vacina_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_vacina_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_vacina_vacina ON flutz.empresa_vacina (vacina_id);

CREATE INDEX idx_empresa_vacina_status ON flutz.empresa_vacina (status_id);

CREATE TRIGGER trg_empresa_vacina_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_vacina
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_vacina IS
  'Vacinas habilitadas para uso pela clínica.';

CREATE TABLE flutz.empresa_doenca (
  empresa_doenca_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  doenca_id INT NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_doenca_id PRIMARY KEY (empresa_doenca_id),
  CONSTRAINT uk_empresa_doenca UNIQUE (empresa_id, doenca_id),


  CONSTRAINT fk_empresa_doenca_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_doenca_doenca
    FOREIGN KEY (doenca_id)
    REFERENCES doenca (doenca_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_doenca_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_doenca_doenca ON flutz.empresa_doenca (doenca_id);

CREATE INDEX idx_empresa_doenca_status ON flutz.empresa_doenca (status_id);

CREATE TRIGGER trg_empresa_doenca_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_doenca
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_doenca IS
  'Doenças habilitadas no prontuário da clínica.';

CREATE TABLE flutz.empresa_pet_especie (
  empresa_pet_especie_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  pet_especie_id INT NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_pet_especie_id PRIMARY KEY (empresa_pet_especie_id),
  CONSTRAINT uk_empresa_pet_especie UNIQUE (empresa_id, pet_especie_id),


  CONSTRAINT fk_empresa_pet_especie_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_pet_especie_especie
    FOREIGN KEY (pet_especie_id)
    REFERENCES pet_especie (pet_especie_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_pet_especie_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_pet_especie_especie ON flutz.empresa_pet_especie (pet_especie_id);

CREATE INDEX idx_empresa_pet_especie_status ON flutz.empresa_pet_especie (status_id);

CREATE TRIGGER trg_empresa_pet_especie_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_pet_especie
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_pet_especie IS
  'Espécies atendidas pela clínica.';

CREATE TABLE flutz.empresa_pet_raca (
  empresa_pet_raca_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  pet_raca_id INT NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_empresa_pet_raca_id PRIMARY KEY (empresa_pet_raca_id),
  CONSTRAINT uk_empresa_pet_raca UNIQUE (empresa_id, pet_raca_id),


  CONSTRAINT fk_empresa_pet_raca_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_pet_raca_raca
    FOREIGN KEY (pet_raca_id)
    REFERENCES pet_raca (pet_raca_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_empresa_pet_raca_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_empresa_pet_raca_raca ON flutz.empresa_pet_raca (pet_raca_id);

CREATE INDEX idx_empresa_pet_raca_status ON flutz.empresa_pet_raca (status_id);

CREATE TRIGGER trg_empresa_pet_raca_ultima_atualizacao
BEFORE UPDATE ON flutz.empresa_pet_raca
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.empresa_pet_raca IS
  'Raças utilizadas pela clínica.';

-- -----------------------------------------------------------------------------
-- 6. Pets e prontuário
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.pet (
  pet_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  cliente_id INT NOT NULL,
  pet_especie_id INT NOT NULL,
  pet_raca_id INT NULL,
  nome_pet VARCHAR(80) NOT NULL,
  sexo CHAR(1) NOT NULL,
  data_aniversario DATE NULL,
  peso DECIMAL(6,2) NULL,
  numero_microchip VARCHAR(45) NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_pet_id PRIMARY KEY (pet_id),





  CONSTRAINT uk_pet_empresa_microchip UNIQUE (empresa_id, numero_microchip),
  CONSTRAINT chk_pet_sexo
    CHECK (sexo IN ('M', 'F', 'I')),
  CONSTRAINT chk_pet_peso
    CHECK (peso IS NULL OR peso > 0),
  CONSTRAINT fk_pet_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_pet_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_pet_especie
    FOREIGN KEY (pet_especie_id)
    REFERENCES pet_especie (pet_especie_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_pet_raca
    FOREIGN KEY (pet_raca_id)
    REFERENCES pet_raca (pet_raca_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_pet_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_pet_empresa_cliente ON flutz.pet (empresa_id, cliente_id);

CREATE INDEX idx_pet_cliente ON flutz.pet (cliente_id);

CREATE INDEX idx_pet_especie ON flutz.pet (pet_especie_id);

CREATE INDEX idx_pet_raca ON flutz.pet (pet_raca_id);

CREATE INDEX idx_pet_status ON flutz.pet (status_id);

CREATE TRIGGER trg_pet_ultima_atualizacao
BEFORE UPDATE ON flutz.pet
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.pet IS
  'Pet cadastrado na clínica. empresa_id é obrigatório para isolamento de tenant.';

CREATE TABLE flutz.colaborador_pet (
  colaborador_pet_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  colaborador_id INT NOT NULL,
  pet_id INT NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_colaborador_pet_id PRIMARY KEY (colaborador_pet_id),
  CONSTRAINT uk_colaborador_pet UNIQUE (colaborador_id, pet_id),


  CONSTRAINT fk_colaborador_pet_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_colaborador_pet_pet
    FOREIGN KEY (pet_id)
    REFERENCES pet (pet_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_colaborador_pet_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_colaborador_pet_pet ON flutz.colaborador_pet (pet_id);

CREATE INDEX idx_colaborador_pet_status ON flutz.colaborador_pet (status_id);

CREATE TRIGGER trg_colaborador_pet_ultima_atualizacao
BEFORE UPDATE ON flutz.colaborador_pet
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.colaborador_pet IS
  'Veterinário(s) de referência do pet. Antes: colaborador_tutor_pet.';

CREATE TABLE flutz.historico_vacinacao (
  historico_vacinacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  pet_id INT NOT NULL,
  vacina_id INT NOT NULL,
  colaborador_id INT NULL,
  atendimento_id INT NULL,
  data_aplicacao DATE NOT NULL,
  data_proxima_dose DATE NULL,
  lote VARCHAR(80) NULL,
  observacoes TEXT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_historico_vacinacao_id PRIMARY KEY (historico_vacinacao_id),




  CONSTRAINT chk_historico_vacinacao_datas
    CHECK (data_proxima_dose IS NULL OR data_proxima_dose >= data_aplicacao),
  CONSTRAINT fk_historico_vacinacao_pet
    FOREIGN KEY (pet_id)
    REFERENCES pet (pet_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_historico_vacinacao_vacina
    FOREIGN KEY (vacina_id)
    REFERENCES vacina (vacina_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_historico_vacinacao_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX idx_historico_vacinacao_pet_data ON flutz.historico_vacinacao (pet_id, data_aplicacao);

CREATE INDEX idx_historico_vacinacao_vacina ON flutz.historico_vacinacao (vacina_id);

CREATE INDEX idx_historico_vacinacao_colaborador ON flutz.historico_vacinacao (colaborador_id);

CREATE INDEX idx_historico_vacinacao_atendimento ON flutz.historico_vacinacao (atendimento_id);

CREATE TRIGGER trg_historico_vacinacao_ultima_atualizacao
BEFORE UPDATE ON flutz.historico_vacinacao
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.historico_vacinacao IS
  'Aplicações de vacina. Tenant via pet.empresa_id. atendimento_id amarra à visita quando houver.';

COMMENT ON COLUMN flutz.historico_vacinacao.atendimento_id IS
  'NULL = registro só de prontuário (importação/legado).';

CREATE TABLE flutz.historico_doenca (
  historico_doenca_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  pet_id INT NOT NULL,
  doenca_id INT NOT NULL,
  colaborador_id INT NULL,
  atendimento_id INT NULL,
  data_diagnostico DATE NOT NULL,
  data_cura DATE NULL,
  observacoes TEXT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_historico_doenca_id PRIMARY KEY (historico_doenca_id),




  CONSTRAINT chk_historico_doenca_datas
    CHECK (data_cura IS NULL OR data_cura >= data_diagnostico),
  CONSTRAINT fk_historico_doenca_pet
    FOREIGN KEY (pet_id)
    REFERENCES pet (pet_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_historico_doenca_doenca
    FOREIGN KEY (doenca_id)
    REFERENCES doenca (doenca_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_historico_doenca_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX idx_historico_doenca_pet_data ON flutz.historico_doenca (pet_id, data_diagnostico);

CREATE INDEX idx_historico_doenca_doenca ON flutz.historico_doenca (doenca_id);

CREATE INDEX idx_historico_doenca_colaborador ON flutz.historico_doenca (colaborador_id);

CREATE INDEX idx_historico_doenca_atendimento ON flutz.historico_doenca (atendimento_id);

CREATE TRIGGER trg_historico_doenca_ultima_atualizacao
BEFORE UPDATE ON flutz.historico_doenca
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.historico_doenca IS
  'Ocorrências de doença no pet. Tenant via pet.empresa_id. atendimento_id amarra à visita quando houver.';

COMMENT ON COLUMN flutz.historico_doenca.atendimento_id IS
  'NULL = registro só de prontuário (importação/legado).';

CREATE TABLE flutz.notificacao_vacina (
  notificacao_vacina_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  historico_vacinacao_id INT NOT NULL,
  empresa_id INT NOT NULL,
  cliente_id INT NOT NULL,
  canal VARCHAR(20) NOT NULL,
  status_envio VARCHAR(30) NOT NULL,
  data_proxima_dose_ref DATE NULL,
  detalhe_erro VARCHAR(255) NULL,
  data_envio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_notificacao_vacina_id PRIMARY KEY (notificacao_vacina_id),



  CONSTRAINT chk_notificacao_vacina_canal
    CHECK (canal IN ('WHATSAPP', 'EMAIL', 'SMS')),
  CONSTRAINT chk_notificacao_vacina_status
    CHECK (status_envio IN ('ENVIADA', 'FALHOU', 'IGNORADA')),
  CONSTRAINT fk_notificacao_vacina_historico
    FOREIGN KEY (historico_vacinacao_id)
    REFERENCES historico_vacinacao (historico_vacinacao_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_notificacao_vacina_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_notificacao_vacina_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_notificacao_vacina_historico ON flutz.notificacao_vacina (historico_vacinacao_id, data_envio);

CREATE INDEX idx_notificacao_vacina_empresa_data ON flutz.notificacao_vacina (empresa_id, data_envio);

CREATE INDEX idx_notificacao_vacina_cliente ON flutz.notificacao_vacina (cliente_id);

COMMENT ON TABLE flutz.notificacao_vacina IS
  'Tentativas de aviso de vencimento de vacina. Evita reenvio cego.';

COMMENT ON COLUMN flutz.notificacao_vacina.data_proxima_dose_ref IS
  'Foto da data avisada.';

COMMENT ON COLUMN flutz.notificacao_vacina.data_envio IS
  'Instante da tentativa de envio.';

-- FKs opcionais de avaliacao_cliente para cliente/pet (criadas após pet)

ALTER TABLE flutz.avaliacao_cliente
  ADD CONSTRAINT fk_avaliacao_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES flutz.cliente (cliente_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  ADD CONSTRAINT fk_avaliacao_pet
    FOREIGN KEY (pet_id)
    REFERENCES flutz.pet (pet_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

-- -----------------------------------------------------------------------------
-- 7. Agenda e atendimento
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.agendamento (
  agendamento_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  cliente_id INT NOT NULL,
  pet_id INT NOT NULL,
  colaborador_id INT NULL,
  empresa_servico_id INT NULL,
  agendamento_status_id INT NOT NULL,
  origem VARCHAR(20) NOT NULL,
  colaborador_criacao_id INT NULL,
  data_hora_inicio TIMESTAMP NOT NULL,
  data_hora_fim TIMESTAMP NULL,
  observacoes TEXT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_agendamento_id PRIMARY KEY (agendamento_id),








  CONSTRAINT chk_agendamento_periodo
    CHECK (data_hora_fim IS NULL OR data_hora_fim >= data_hora_inicio),
  CONSTRAINT chk_agendamento_fim_quando_profissional
    CHECK (colaborador_id IS NULL OR data_hora_fim IS NOT NULL),
  CONSTRAINT chk_agendamento_origem
    CHECK (
      (origem = 'CLIENTE' AND colaborador_criacao_id IS NULL)
      OR (origem = 'COLABORADOR' AND colaborador_criacao_id IS NOT NULL)
    ),
  CONSTRAINT fk_agendamento_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_pet
    FOREIGN KEY (pet_id)
    REFERENCES pet (pet_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_colaborador_criacao
    FOREIGN KEY (colaborador_criacao_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_servico
    FOREIGN KEY (empresa_servico_id)
    REFERENCES empresa_servico (empresa_servico_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_agendamento_status
    FOREIGN KEY (agendamento_status_id)
    REFERENCES agendamento_status (agendamento_status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_agendamento_empresa_inicio ON flutz.agendamento (empresa_id, data_hora_inicio);

CREATE INDEX idx_agendamento_cliente ON flutz.agendamento (cliente_id);

CREATE INDEX idx_agendamento_pet ON flutz.agendamento (pet_id);

CREATE INDEX idx_agendamento_colaborador_inicio ON flutz.agendamento (colaborador_id, data_hora_inicio);

CREATE INDEX idx_agendamento_servico ON flutz.agendamento (empresa_servico_id);

CREATE INDEX idx_agendamento_status ON flutz.agendamento (agendamento_status_id);

CREATE INDEX idx_agendamento_origem ON flutz.agendamento (empresa_id, origem);

CREATE INDEX idx_agendamento_criacao ON flutz.agendamento (colaborador_criacao_id);

CREATE TRIGGER trg_agendamento_ultima_atualizacao
BEFORE UPDATE ON flutz.agendamento
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.agendamento IS
  'Compromisso futuro. origem diz se o tutor ou a clínica marcou.';

COMMENT ON COLUMN flutz.agendamento.origem IS
  'CLIENTE = tutor no app; COLABORADOR = clínica marcou.';

COMMENT ON COLUMN flutz.agendamento.colaborador_criacao_id IS
  'Preenchido só quando origem = COLABORADOR.';

CREATE TABLE flutz.atendimento (
  atendimento_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  cliente_id INT NOT NULL,
  pet_id INT NOT NULL,
  agendamento_id INT NULL,
  empresa_servico_id INT NULL,
  atendimento_status_id INT NOT NULL,
  origem VARCHAR(20) NOT NULL,
  colaborador_criacao_id INT NULL,
  resumo_cliente TEXT NULL,
  detalhes TEXT NULL,
  data_inicio TIMESTAMP NULL,
  data_fim TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_atendimento_id PRIMARY KEY (atendimento_id),
  CONSTRAINT uk_atendimento_agendamento UNIQUE (agendamento_id),







  CONSTRAINT chk_atendimento_periodo
    CHECK (data_fim IS NULL OR data_inicio IS NULL OR data_fim >= data_inicio),
  CONSTRAINT chk_atendimento_origem
    CHECK (
      (origem = 'CLIENTE' AND colaborador_criacao_id IS NULL)
      OR (origem = 'COLABORADOR' AND colaborador_criacao_id IS NOT NULL)
    ),
  CONSTRAINT fk_atendimento_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_pet
    FOREIGN KEY (pet_id)
    REFERENCES pet (pet_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_agendamento
    FOREIGN KEY (agendamento_id)
    REFERENCES agendamento (agendamento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_servico
    FOREIGN KEY (empresa_servico_id)
    REFERENCES empresa_servico (empresa_servico_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_colaborador_criacao
    FOREIGN KEY (colaborador_criacao_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_status
    FOREIGN KEY (atendimento_status_id)
    REFERENCES atendimento_status (atendimento_status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_atendimento_empresa_inicio ON flutz.atendimento (empresa_id, data_inicio);

CREATE INDEX idx_atendimento_cliente ON flutz.atendimento (cliente_id);

CREATE INDEX idx_atendimento_pet ON flutz.atendimento (pet_id);

CREATE INDEX idx_atendimento_servico ON flutz.atendimento (empresa_servico_id);

CREATE INDEX idx_atendimento_status ON flutz.atendimento (atendimento_status_id);

CREATE INDEX idx_atendimento_origem ON flutz.atendimento (empresa_id, origem);

CREATE INDEX idx_atendimento_criacao ON flutz.atendimento (colaborador_criacao_id);

CREATE TRIGGER trg_atendimento_ultima_atualizacao
BEFORE UPDATE ON flutz.atendimento
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.atendimento IS
  'Ato clínico realizado. 0..1 com agendamento. Serviço e vacinas da visita ligam aqui.';

COMMENT ON COLUMN flutz.atendimento.empresa_servico_id IS
  'Serviço realizado no ato (pode diferir do agendado).';

COMMENT ON COLUMN flutz.atendimento.origem IS
  'CLIENTE ou COLABORADOR. Walk-in da recepção = COLABORADOR.';

COMMENT ON COLUMN flutz.atendimento.colaborador_criacao_id IS
  'Quem abriu a visita quando origem = COLABORADOR.';

COMMENT ON COLUMN flutz.atendimento.resumo_cliente IS
  'Relato do tutor (queixa/objetivo). Ele preenche e acompanha.';

COMMENT ON COLUMN flutz.atendimento.detalhes IS
  'Nota clínica interna do colaborador. O tutor não vê.';

ALTER TABLE flutz.historico_vacinacao
  ADD CONSTRAINT fk_historico_vacinacao_atendimento
    FOREIGN KEY (atendimento_id)
    REFERENCES flutz.atendimento (atendimento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

ALTER TABLE flutz.historico_doenca
  ADD CONSTRAINT fk_historico_doenca_atendimento
    FOREIGN KEY (atendimento_id)
    REFERENCES flutz.atendimento (atendimento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

CREATE TABLE flutz.atendimento_colaborador (
  atendimento_colaborador_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  atendimento_id INT NOT NULL,
  colaborador_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_atendimento_colaborador_id PRIMARY KEY (atendimento_colaborador_id),
  CONSTRAINT uk_atendimento_colaborador UNIQUE (atendimento_id, colaborador_id),

  CONSTRAINT fk_atendimento_colaborador_atendimento
    FOREIGN KEY (atendimento_id)
    REFERENCES atendimento (atendimento_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_colaborador_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_atendimento_colaborador_colab ON flutz.atendimento_colaborador (colaborador_id);

CREATE TRIGGER trg_atendimento_colaborador_ultima_atualizacao
BEFORE UPDATE ON flutz.atendimento_colaborador
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.atendimento_colaborador IS
  'N:N — profissionais envolvidos no atendimento.';

CREATE TABLE flutz.atendimento_andamento (
  atendimento_andamento_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  atendimento_id INT NOT NULL,
  colaborador_id INT NOT NULL,
  detalhes_colaborador TEXT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_atendimento_andamento_id PRIMARY KEY (atendimento_andamento_id),


  CONSTRAINT fk_atendimento_andamento_atendimento
    FOREIGN KEY (atendimento_id)
    REFERENCES atendimento (atendimento_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_atendimento_andamento_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_andamento_atendimento ON flutz.atendimento_andamento (atendimento_id, data_criacao);

CREATE INDEX idx_andamento_colaborador ON flutz.atendimento_andamento (colaborador_id);

COMMENT ON TABLE flutz.atendimento_andamento IS
  'Linha do tempo do atendimento. FK atendimento_id era omissa/ambígua no modelo antigo.';

-- -----------------------------------------------------------------------------
-- 8. Doações
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.doacao (
  doacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  titulo VARCHAR(150) NOT NULL,
  texto TEXT NULL,
  meta_valor DECIMAL(10,2) NULL,
  data_inicio DATE NULL,
  data_fim DATE NULL,
  imagem_principal_url VARCHAR(500) NULL,
  ordem INT NOT NULL DEFAULT 1,
  visivel_pagina BOOLEAN NOT NULL DEFAULT TRUE,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_doacao_id PRIMARY KEY (doacao_id),


  CONSTRAINT chk_doacao_datas
    CHECK (data_fim IS NULL OR data_inicio IS NULL OR data_fim >= data_inicio),
  CONSTRAINT chk_doacao_meta
    CHECK (meta_valor IS NULL OR meta_valor >= 0),
  CONSTRAINT chk_doacao_visivel
    CHECK (visivel_pagina IN (FALSE, TRUE)),
  CONSTRAINT fk_doacao_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_doacao_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_doacao_empresa_status ON flutz.doacao (empresa_id, status_id);

CREATE INDEX idx_doacao_empresa_ordem ON flutz.doacao (empresa_id, visivel_pagina, ordem);

CREATE TRIGGER trg_doacao_ultima_atualizacao
BEFORE UPDATE ON flutz.doacao
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.doacao IS
  'Campanha de doação da clínica. Valor arrecadado = soma de pagamentos PAGO.';

CREATE TABLE flutz.galeria_doacao (
  galeria_doacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  doacao_id INT NOT NULL,
  imagem_url VARCHAR(500) NOT NULL,
  texto_alternativo VARCHAR(255) NULL,
  ordem INT NOT NULL DEFAULT 1,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_galeria_doacao_id PRIMARY KEY (galeria_doacao_id),

  CONSTRAINT chk_galeria_doacao_ordem
    CHECK (ordem >= 1),
  CONSTRAINT fk_galeria_doacao_doacao
    FOREIGN KEY (doacao_id)
    REFERENCES doacao (doacao_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX idx_galeria_doacao_doacao_ordem ON flutz.galeria_doacao (doacao_id, ordem);

CREATE TRIGGER trg_galeria_doacao_ultima_atualizacao
BEFORE UPDATE ON flutz.galeria_doacao
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.galeria_doacao IS
  'Imagens da campanha. Tenant via doacao.empresa_id.';

-- -----------------------------------------------------------------------------
-- 9. Pagamentos da clínica (receita da empresa)
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.conta_pagamento (
  conta_pagamento_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  provider VARCHAR(40) NOT NULL,
  account_id VARCHAR(120) NOT NULL,
  status_conta VARCHAR(20) NOT NULL,
  connected_at TIMESTAMP NULL,
  disconnected_at TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_conta_pagamento_id PRIMARY KEY (conta_pagamento_id),
  CONSTRAINT uk_conta_pagamento_provider_account UNIQUE (provider, account_id),

  CONSTRAINT chk_conta_pagamento_status
    CHECK (status_conta IN ('PENDENTE', 'CONECTADA', 'DESCONECTADA', 'REJEITADA')),
  CONSTRAINT fk_conta_pagamento_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_conta_pagamento_empresa_status ON flutz.conta_pagamento (empresa_id, status_conta);

CREATE TRIGGER trg_conta_pagamento_ultima_atualizacao
BEFORE UPDATE ON flutz.conta_pagamento
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.conta_pagamento IS
  'Conta conectada no provedor. 1:N para permitir troca de provider sem perder histórico.';

CREATE TABLE flutz.pagamento (
  pagamento_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  conta_pagamento_id INT NULL,
  cliente_id INT NULL,
  tipo_origem VARCHAR(20) NOT NULL,
  agendamento_id INT NULL,
  atendimento_id INT NULL,
  empresa_servico_id INT NULL,
  doacao_id INT NULL,
  valor DECIMAL(10,2) NOT NULL,
  moeda CHAR(3) NOT NULL DEFAULT 'BRL',
  status_pagamento VARCHAR(20) NOT NULL,
  provider VARCHAR(40) NULL,
  provider_pagamento_id VARCHAR(120) NULL,
  metodo VARCHAR(40) NULL,
  pago_em TIMESTAMP NULL,
  descricao VARCHAR(255) NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_pagamento_id PRIMARY KEY (pagamento_id),
  CONSTRAINT uk_pagamento_provider_ref UNIQUE (provider, provider_pagamento_id),







  CONSTRAINT chk_pagamento_valor
    CHECK (valor > 0),
  CONSTRAINT chk_pagamento_tipo
    CHECK (tipo_origem IN ('ATENDIMENTO', 'SERVICO', 'DOACAO', 'AGENDAMENTO', 'OUTRO')),
  CONSTRAINT chk_pagamento_status
    CHECK (status_pagamento IN ('PENDENTE', 'PAGO', 'CANCELADO', 'ESTORNADO', 'FALHOU')),
  CONSTRAINT chk_pagamento_origem_fk
    CHECK (
      (tipo_origem = 'ATENDIMENTO' AND atendimento_id IS NOT NULL)
      OR (tipo_origem = 'SERVICO' AND empresa_servico_id IS NOT NULL)
      OR (tipo_origem = 'DOACAO' AND doacao_id IS NOT NULL)
      OR (tipo_origem = 'AGENDAMENTO' AND agendamento_id IS NOT NULL)
      OR (tipo_origem = 'OUTRO')
    ),
  CONSTRAINT fk_pagamento_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_pagamento_conta
    FOREIGN KEY (conta_pagamento_id)
    REFERENCES conta_pagamento (conta_pagamento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_pagamento_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_pagamento_agendamento
    FOREIGN KEY (agendamento_id)
    REFERENCES agendamento (agendamento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_pagamento_atendimento
    FOREIGN KEY (atendimento_id)
    REFERENCES atendimento (atendimento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_pagamento_servico
    FOREIGN KEY (empresa_servico_id)
    REFERENCES empresa_servico (empresa_servico_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_pagamento_doacao
    FOREIGN KEY (doacao_id)
    REFERENCES doacao (doacao_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX idx_pagamento_empresa_status ON flutz.pagamento (empresa_id, status_pagamento);

CREATE INDEX idx_pagamento_cliente ON flutz.pagamento (cliente_id);

CREATE INDEX idx_pagamento_conta ON flutz.pagamento (conta_pagamento_id);

CREATE INDEX idx_pagamento_agendamento ON flutz.pagamento (agendamento_id);

CREATE INDEX idx_pagamento_atendimento ON flutz.pagamento (atendimento_id);

CREATE INDEX idx_pagamento_servico ON flutz.pagamento (empresa_servico_id);

CREATE INDEX idx_pagamento_doacao ON flutz.pagamento (doacao_id);

CREATE TRIGGER trg_pagamento_ultima_atualizacao
BEFORE UPDATE ON flutz.pagamento
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.pagamento IS
  'Livro único de recebimentos da clínica (consulta, serviço, doação). Não inclui mensalidade do SaaS.';

-- -----------------------------------------------------------------------------
-- 10. Assinatura / mensalidade (receita da plataforma)
-- A conta recebedora da plataforma fica no .env, não neste modelo.
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.assinatura (
  assinatura_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  plano_id INT NOT NULL,
  status_assinatura VARCHAR(20) NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NULL,
  data_proximo_vencimento DATE NULL,
  dias_tolerancia INT NOT NULL DEFAULT 3,
  data_cancelamento TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_assinatura_id PRIMARY KEY (assinatura_id),



  CONSTRAINT chk_assinatura_status
    CHECK (status_assinatura IN ('TRIAL', 'ATIVA', 'INADIMPLENTE', 'SUSPENSA', 'CANCELADA')),
  CONSTRAINT chk_assinatura_tolerancia
    CHECK (dias_tolerancia >= 0),
  CONSTRAINT chk_assinatura_periodo
    CHECK (data_fim IS NULL OR data_fim >= data_inicio),
  CONSTRAINT fk_assinatura_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_assinatura_plano
    FOREIGN KEY (plano_id)
    REFERENCES plano (plano_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_assinatura_empresa_status ON flutz.assinatura (empresa_id, status_assinatura);

CREATE INDEX idx_assinatura_plano ON flutz.assinatura (plano_id);

CREATE INDEX idx_assinatura_vencimento ON flutz.assinatura (status_assinatura, data_proximo_vencimento);

CREATE TRIGGER trg_assinatura_ultima_atualizacao
BEFORE UPDATE ON flutz.assinatura
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

CREATE TABLE flutz.fatura_assinatura (
  fatura_assinatura_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  assinatura_id INT NOT NULL,
  empresa_id INT NOT NULL,
  competencia DATE NOT NULL,
  valor_bruto DECIMAL(10,2) NOT NULL,
  token_id INT NULL,
  codigo_token_aplicado VARCHAR(80) NULL,
  percentual_desconto_aplicado DECIMAL(5,2) NULL,
  valor DECIMAL(10,2) NOT NULL,
  moeda CHAR(3) NOT NULL DEFAULT 'BRL',
  status_fatura VARCHAR(20) NOT NULL,
  data_vencimento DATE NOT NULL,
  data_pagamento TIMESTAMP NULL,
  provider VARCHAR(40) NULL,
  provider_fatura_id VARCHAR(120) NULL,
  provider_pagamento_id VARCHAR(120) NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_fatura_assinatura_id PRIMARY KEY (fatura_assinatura_id),
  CONSTRAINT uk_fatura_assinatura_competencia UNIQUE (assinatura_id, competencia),




  CONSTRAINT chk_fatura_status
    CHECK (status_fatura IN ('PENDENTE', 'PAGA', 'ATRASADA', 'CANCELADA')),
  CONSTRAINT chk_fatura_valor_bruto
    CHECK (valor_bruto >= 0),
  CONSTRAINT chk_fatura_valor
    CHECK (valor >= 0 AND valor <= valor_bruto),
  CONSTRAINT chk_fatura_token_auditoria
    CHECK (
      (
        token_id IS NULL
        AND codigo_token_aplicado IS NULL
        AND percentual_desconto_aplicado IS NULL
      )
      OR (
        token_id IS NOT NULL
        AND codigo_token_aplicado IS NOT NULL
        AND percentual_desconto_aplicado IS NOT NULL
        AND percentual_desconto_aplicado >= 0
        AND percentual_desconto_aplicado <= 100
      )
    ),
  CONSTRAINT fk_fatura_assinatura
    FOREIGN KEY (assinatura_id)
    REFERENCES assinatura (assinatura_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_fatura_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_fatura_token
    FOREIGN KEY (token_id)
    REFERENCES token (token_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_fatura_empresa ON flutz.fatura_assinatura (empresa_id);

CREATE INDEX idx_fatura_token ON flutz.fatura_assinatura (token_id);

CREATE INDEX idx_fatura_status_vencimento ON flutz.fatura_assinatura (status_fatura, data_vencimento);

CREATE INDEX idx_fatura_provider_ref ON flutz.fatura_assinatura (provider, provider_fatura_id);

CREATE TRIGGER trg_fatura_assinatura_ultima_atualizacao
BEFORE UPDATE ON flutz.fatura_assinatura
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.fatura_assinatura IS
  'Fatura mensal da clínica. token_id NULL = sem cupom. Snapshots auditam o desconto aplicado.';

COMMENT ON COLUMN flutz.fatura_assinatura.competencia IS
  'Primeiro dia do mês de referência';

COMMENT ON COLUMN flutz.fatura_assinatura.valor_bruto IS
  'Preço do plano antes do cupom.';

COMMENT ON COLUMN flutz.fatura_assinatura.token_id IS
  'NULL = fatura sem desconto.';

COMMENT ON COLUMN flutz.fatura_assinatura.codigo_token_aplicado IS
  'Foto do código no momento do uso.';

COMMENT ON COLUMN flutz.fatura_assinatura.percentual_desconto_aplicado IS
  'Foto do percentual no momento do uso.';

COMMENT ON COLUMN flutz.fatura_assinatura.valor IS
  'Valor líquido cobrado (após desconto, se houver).';

-- -----------------------------------------------------------------------------
-- 11. Chat
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.chat (
  chat_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NOT NULL,
  cliente_id INT NOT NULL,
  pet_id INT NULL,
  agendamento_id INT NULL,
  atendimento_id INT NULL,
  chat_motivo_id INT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_chat_id PRIMARY KEY (chat_id),






  CONSTRAINT fk_chat_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_pet
    FOREIGN KEY (pet_id)
    REFERENCES pet (pet_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_agendamento
    FOREIGN KEY (agendamento_id)
    REFERENCES agendamento (agendamento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_atendimento
    FOREIGN KEY (atendimento_id)
    REFERENCES atendimento (atendimento_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_motivo
    FOREIGN KEY (chat_motivo_id)
    REFERENCES chat_motivo (chat_motivo_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_chat_empresa_status ON flutz.chat (empresa_id, status_id);

CREATE INDEX idx_chat_cliente ON flutz.chat (cliente_id);

CREATE INDEX idx_chat_pet ON flutz.chat (pet_id);

CREATE INDEX idx_chat_agendamento ON flutz.chat (agendamento_id);

CREATE INDEX idx_chat_atendimento ON flutz.chat (atendimento_id);

CREATE INDEX idx_chat_motivo ON flutz.chat (chat_motivo_id);

CREATE TRIGGER trg_chat_ultima_atualizacao
BEFORE UPDATE ON flutz.chat
FOR EACH ROW
EXECUTE FUNCTION flutz.set_ultima_atualizacao();

COMMENT ON TABLE flutz.chat IS
  'Chat do tutor com a clínica. pet_id 0..1: NULL = pergunta geral.';

COMMENT ON COLUMN flutz.chat.pet_id IS
  'NULL = conversa geral com a clínica, sem animal.';

CREATE TABLE flutz.chat_mensagem (
  chat_mensagem_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  chat_id INT NOT NULL,
  remetente_tipo VARCHAR(20) NOT NULL,
  remetente_id INT NOT NULL,
  mensagem TEXT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_chat_mensagem_id PRIMARY KEY (chat_mensagem_id),

  CONSTRAINT chk_chat_mensagem_remetente
    CHECK (remetente_tipo IN ('CLIENTE', 'COLABORADOR')),
  CONSTRAINT fk_chat_mensagem_chat
    FOREIGN KEY (chat_id)
    REFERENCES chat (chat_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX idx_chat_mensagem_chat ON flutz.chat_mensagem (chat_id, data_criacao);

COMMENT ON TABLE flutz.chat_mensagem IS
  'Mensagens do chat. Substitui o flag cliente TINYINT + coluna chatcol.';

CREATE TABLE flutz.chat_colaborador_responsavel (
  chat_colaborador_responsavel_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  chat_id INT NOT NULL,
  colaborador_id INT NOT NULL,
  status_id INT NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_chat_colaborador_responsavel_id PRIMARY KEY (chat_colaborador_responsavel_id),
  CONSTRAINT uk_chat_colaborador_responsavel UNIQUE (chat_id, colaborador_id),


  CONSTRAINT fk_chat_resp_chat
    FOREIGN KEY (chat_id)
    REFERENCES chat (chat_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_resp_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_resp_status
    FOREIGN KEY (status_id)
    REFERENCES status (status_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_chat_resp_colaborador ON flutz.chat_colaborador_responsavel (colaborador_id);

CREATE INDEX idx_chat_resp_status ON flutz.chat_colaborador_responsavel (status_id);

COMMENT ON TABLE flutz.chat_colaborador_responsavel IS
  'Colaboradores responsáveis pelo chat.';

CREATE TABLE flutz.chat_finalizacao (
  chat_finalizacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  chat_id INT NOT NULL,
  colaborador_id INT NOT NULL,
  observacoes TEXT NULL,
  data_finalizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_chat_finalizacao_id PRIMARY KEY (chat_finalizacao_id),
  CONSTRAINT uk_chat_finalizacao_chat UNIQUE (chat_id),

  CONSTRAINT fk_chat_finalizacao_chat
    FOREIGN KEY (chat_id)
    REFERENCES chat (chat_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_finalizacao_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_chat_finalizacao_colaborador ON flutz.chat_finalizacao (colaborador_id);

COMMENT ON TABLE flutz.chat_finalizacao IS
  'Encerramento do chat. 1:1 com chat. Removido chat_cliente_id redundante.';

CREATE TABLE flutz.chat_avaliacao_colaborador (
  chat_avaliacao_colaborador_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  chat_id INT NOT NULL,
  cliente_id INT NOT NULL,
  colaborador_id INT NOT NULL,
  nota DECIMAL(2,1) NOT NULL,
  sugestao TEXT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_chat_avaliacao_colaborador_id PRIMARY KEY (chat_avaliacao_colaborador_id),
  CONSTRAINT uk_chat_avaliacao UNIQUE (chat_id, colaborador_id),


  CONSTRAINT chk_chat_avaliacao_nota
    CHECK (nota >= 0 AND nota <= 5),
  CONSTRAINT fk_chat_avaliacao_chat
    FOREIGN KEY (chat_id)
    REFERENCES chat (chat_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_avaliacao_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES cliente (cliente_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_chat_avaliacao_colaborador
    FOREIGN KEY (colaborador_id)
    REFERENCES colaborador (colaborador_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_chat_avaliacao_cliente ON flutz.chat_avaliacao_colaborador (cliente_id);

CREATE INDEX idx_chat_avaliacao_colaborador ON flutz.chat_avaliacao_colaborador (colaborador_id);

COMMENT ON TABLE flutz.chat_avaliacao_colaborador IS
  'Avaliação do atendimento via chat. chat_id era ausente no modelo antigo.';

-- -----------------------------------------------------------------------------
-- 12. LGPD e auditoria. Não gravar senha_hash nem segredo de gateway no JSON.
-- EXCLUSAO de titular no SaaS = anonimização (RESTRICT impede apagar fatos).
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.solicitacao_titular (
  solicitacao_titular_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NULL,
  titular_tipo VARCHAR(30) NOT NULL,
  titular_id INT NOT NULL,
  tipo_solicitacao VARCHAR(40) NOT NULL,
  status_solicitacao VARCHAR(20) NOT NULL,
  detalhamento TEXT NULL,
  motivo_negativa TEXT NULL,
  data_solicitacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_conclusao TIMESTAMP NULL,
  CONSTRAINT pk_solicitacao_titular_id PRIMARY KEY (solicitacao_titular_id),


  CONSTRAINT chk_solicitacao_titular_tipo_pessoa
    CHECK (titular_tipo IN ('CLIENTE', 'COLABORADOR', 'ADMINISTRADOR_SISTEMA')),
  CONSTRAINT chk_solicitacao_titular_tipo
    CHECK (tipo_solicitacao IN (
      'ACESSO',
      'CORRECAO',
      'ANONIMIZACAO',
      'EXCLUSAO',
      'PORTABILIDADE',
      'REVOGACAO_CONSENTIMENTO'
    )),
  CONSTRAINT chk_solicitacao_titular_status
    CHECK (status_solicitacao IN ('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'NEGADA')),
  CONSTRAINT chk_solicitacao_titular_conclusao
    CHECK (
      (status_solicitacao IN ('ABERTA', 'EM_ANDAMENTO') AND data_conclusao IS NULL)
      OR (status_solicitacao IN ('CONCLUIDA', 'NEGADA') AND data_conclusao IS NOT NULL)
    ),
  CONSTRAINT fk_solicitacao_titular_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_solicitacao_titular_empresa ON flutz.solicitacao_titular (empresa_id, status_solicitacao);

CREATE INDEX idx_solicitacao_titular_pessoa ON flutz.solicitacao_titular (titular_tipo, titular_id, data_solicitacao);

COMMENT ON TABLE flutz.solicitacao_titular IS
  'Pedido LGPD do titular. EXCLUSAO é atendida por anonimização, não por DELETE físico.';

COMMENT ON COLUMN flutz.solicitacao_titular.empresa_id IS
  'NULL = pedido à plataforma (cadastro global do tutor).';

CREATE TABLE flutz.auditoria_acao (
  auditoria_acao_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  empresa_id INT NULL,
  ator_tipo VARCHAR(30) NOT NULL,
  ator_id INT NOT NULL,
  pagina VARCHAR(255) NULL,
  botao VARCHAR(120) NULL,
  detalhamento TEXT NOT NULL,
  endereco_ip VARCHAR(45) NULL,
  user_agent VARCHAR(500) NULL,
  data_acao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  anonimizado_em TIMESTAMP NULL,
  CONSTRAINT pk_auditoria_acao_id PRIMARY KEY (auditoria_acao_id),


  CONSTRAINT chk_auditoria_acao_ator
    CHECK (ator_tipo IN ('CLIENTE', 'COLABORADOR', 'ADMINISTRADOR_SISTEMA')),
  CONSTRAINT fk_auditoria_acao_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa (empresa_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_auditoria_acao_empresa_data ON flutz.auditoria_acao (empresa_id, data_acao);

CREATE INDEX idx_auditoria_acao_ator_data ON flutz.auditoria_acao (ator_tipo, ator_id, data_acao);

COMMENT ON TABLE flutz.auditoria_acao IS
  'Clique/ação de tela. DELETE proibido. UPDATE só para anonimizar.';

COMMENT ON COLUMN flutz.auditoria_acao.empresa_id IS
  'NULL quando a ação é do administrador do SaaS sem tenant.';

COMMENT ON COLUMN flutz.auditoria_acao.ator_id IS
  'ID em cliente, colaborador ou administrador_sistema, conforme ator_tipo.';

COMMENT ON COLUMN flutz.auditoria_acao.detalhamento IS
  'O que o usuário fez na tela (página, botão, intenção).';

COMMENT ON COLUMN flutz.auditoria_acao.data_acao IS
  'Instante em que a ação foi realizada.';

COMMENT ON COLUMN flutz.auditoria_acao.anonimizado_em IS
  'Único UPDATE permitido: redigir IP/UA/detalhe identificável.';

CREATE TABLE flutz.auditoria_dado (
  auditoria_dado_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  auditoria_acao_id INT NULL,
  operacao VARCHAR(10) NOT NULL,
  tabela VARCHAR(64) NOT NULL,
  registro_id INT NOT NULL,
  dados_anteriores JSONB NULL,
  dados_novos JSONB NULL,
  data_acao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  anonimizado_em TIMESTAMP NULL,
  CONSTRAINT pk_auditoria_dado_id PRIMARY KEY (auditoria_dado_id),



  CONSTRAINT chk_auditoria_dado_operacao
    CHECK (operacao IN ('INSERT', 'UPDATE', 'DELETE')),
  CONSTRAINT chk_auditoria_dado_json
    CHECK (
      (operacao = 'INSERT' AND dados_anteriores IS NULL AND dados_novos IS NOT NULL)
      OR (operacao = 'DELETE' AND dados_anteriores IS NOT NULL AND dados_novos IS NULL)
      OR (operacao = 'UPDATE' AND dados_anteriores IS NOT NULL AND dados_novos IS NOT NULL)
    ),
  CONSTRAINT fk_auditoria_dado_acao
    FOREIGN KEY (auditoria_acao_id)
    REFERENCES auditoria_acao (auditoria_acao_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_auditoria_dado_acao ON flutz.auditoria_dado (auditoria_acao_id);

CREATE INDEX idx_auditoria_dado_tabela_registro ON flutz.auditoria_dado (tabela, registro_id);

CREATE INDEX idx_auditoria_dado_operacao_data ON flutz.auditoria_dado (operacao, data_acao);

COMMENT ON TABLE flutz.auditoria_dado IS
  'DML da ação. DELETE proibido. UPDATE só para redigir JSON na anonimização.';

COMMENT ON COLUMN flutz.auditoria_dado.auditoria_acao_id IS
  'NULL = alteração sem clique (job, script, SQL direto).';

COMMENT ON COLUMN flutz.auditoria_dado.dados_anteriores IS
  'Estado antes. NULL em INSERT. Após anonimizar: JSON redigido.';

COMMENT ON COLUMN flutz.auditoria_dado.dados_novos IS
  'Estado depois. NULL em DELETE. Após anonimizar: JSON redigido.';

COMMENT ON COLUMN flutz.auditoria_dado.data_acao IS
  'Instante do INSERT/UPDATE/DELETE.';


-- -----------------------------------------------------------------------------
-- Recuperação de senha (autorizado: token de alta entropia, hash, uso único)
-- Não armazena o token em texto puro. ator_tipo + ator_id apontam para
-- cliente, colaborador ou administrador_sistema.
-- -----------------------------------------------------------------------------

CREATE TABLE flutz.recuperacao_senha (
  recuperacao_senha_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ator_tipo VARCHAR(30) NOT NULL,
  ator_id INTEGER NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  data_expiracao TIMESTAMP NOT NULL,
  utilizado_em TIMESTAMP NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_recuperacao_senha PRIMARY KEY (recuperacao_senha_id),
  CONSTRAINT uk_recuperacao_senha_token_hash UNIQUE (token_hash),
  CONSTRAINT chk_recuperacao_senha_ator
    CHECK (ator_tipo IN ('CLIENTE', 'COLABORADOR', 'ADMINISTRADOR_SISTEMA')),
  CONSTRAINT chk_recuperacao_senha_expiracao
    CHECK (data_expiracao > data_criacao)
);

CREATE INDEX idx_recuperacao_senha_ator
  ON flutz.recuperacao_senha (ator_tipo, ator_id, data_criacao);

CREATE INDEX idx_recuperacao_senha_expiracao
  ON flutz.recuperacao_senha (data_expiracao)
  WHERE utilizado_em IS NULL;

COMMENT ON TABLE flutz.recuperacao_senha IS
  'Token de recuperação de senha. Armazena somente hash. Uso único e validade limitada.';
COMMENT ON COLUMN flutz.recuperacao_senha.token_hash IS
  'Hash do token enviado por e-mail. O token original nunca é persistido.';
COMMENT ON COLUMN flutz.recuperacao_senha.utilizado_em IS
  'Preenchido no consumo. NULL = ainda não usado.';


-- -----------------------------------------------------------------------------
-- Triggers de negócio (equivalentes aos DELIMITER $$ do MySQL)
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION flutz.fn_colaborador_horario_sem_sobrepor()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM flutz.colaborador_horario h
    WHERE h.colaborador_id = NEW.colaborador_id
      AND h.dia_semana = NEW.dia_semana
      AND (TG_OP = 'INSERT' OR h.colaborador_horario_id <> NEW.colaborador_horario_id)
      AND NEW.hora_inicio < h.hora_fim
      AND NEW.hora_fim > h.hora_inicio
  ) THEN
    RAISE EXCEPTION 'Colaborador ja possui faixa de horario sobreposta neste dia.';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_colaborador_horario_sem_sobrepor
BEFORE INSERT OR UPDATE ON flutz.colaborador_horario
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_colaborador_horario_sem_sobrepor();

CREATE OR REPLACE FUNCTION flutz.fn_agendamento_sem_conflito()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.colaborador_id IS NOT NULL THEN
    IF EXISTS (
      SELECT 1
      FROM flutz.agendamento a
      INNER JOIN flutz.agendamento_status s
        ON s.agendamento_status_id = a.agendamento_status_id
      WHERE a.colaborador_id = NEW.colaborador_id
        AND (TG_OP = 'INSERT' OR a.agendamento_id <> NEW.agendamento_id)
        AND (s.codigo IS NULL OR s.codigo NOT IN ('CANCELADO', 'FALTOU'))
        AND NEW.data_hora_inicio < a.data_hora_fim
        AND NEW.data_hora_fim > a.data_hora_inicio
    ) THEN
      RAISE EXCEPTION 'Colaborador ja possui agendamento neste horario.';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_agendamento_sem_conflito
BEFORE INSERT OR UPDATE ON flutz.agendamento
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_agendamento_sem_conflito();

CREATE OR REPLACE FUNCTION flutz.fn_fatura_token_limite()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_limite integer;
  v_usos integer;
BEGIN
  IF NEW.token_id IS NOT NULL THEN
    SELECT usos_maximos_por_empresa
      INTO v_limite
      FROM flutz.token
      WHERE token_id = NEW.token_id;

    IF v_limite IS NOT NULL THEN
      SELECT COUNT(*)
        INTO v_usos
        FROM flutz.fatura_assinatura
        WHERE empresa_id = NEW.empresa_id
          AND token_id = NEW.token_id
          AND status_fatura <> 'CANCELADA'
          AND (TG_OP = 'INSERT' OR fatura_assinatura_id <> NEW.fatura_assinatura_id);

      IF v_usos >= v_limite THEN
        RAISE EXCEPTION 'Token ja atingiu o limite de usos desta empresa.';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_fatura_token_limite
BEFORE INSERT OR UPDATE ON flutz.fatura_assinatura
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_fatura_token_limite();

CREATE OR REPLACE FUNCTION flutz.fn_auditoria_acao_bloquear_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.anonimizado_em IS NOT NULL THEN
    RAISE EXCEPTION 'auditoria_acao ja anonimizada: UPDATE proibido.';
  END IF;
  IF NEW.anonimizado_em IS NULL
     OR NEW.auditoria_acao_id IS DISTINCT FROM OLD.auditoria_acao_id
     OR NEW.empresa_id IS DISTINCT FROM OLD.empresa_id
     OR NEW.ator_tipo IS DISTINCT FROM OLD.ator_tipo
     OR NEW.ator_id IS DISTINCT FROM OLD.ator_id
     OR NEW.pagina IS DISTINCT FROM OLD.pagina
     OR NEW.botao IS DISTINCT FROM OLD.botao
     OR NEW.data_acao IS DISTINCT FROM OLD.data_acao
     OR NEW.endereco_ip IS NOT NULL
     OR NEW.user_agent IS NOT NULL THEN
    RAISE EXCEPTION 'auditoria_acao: UPDATE so para anonimizar (limpar IP/UA e marcar anonimizado_em).';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_auditoria_acao_bloquear_update
BEFORE UPDATE ON flutz.auditoria_acao
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_auditoria_acao_bloquear_update();

CREATE OR REPLACE FUNCTION flutz.fn_auditoria_acao_bloquear_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'auditoria_acao: DELETE proibido. Use anonimizacao.';
END;
$$;

CREATE TRIGGER trg_auditoria_acao_bloquear_delete
BEFORE DELETE ON flutz.auditoria_acao
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_auditoria_acao_bloquear_delete();

CREATE OR REPLACE FUNCTION flutz.fn_auditoria_dado_bloquear_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.anonimizado_em IS NOT NULL THEN
    RAISE EXCEPTION 'auditoria_dado ja anonimizada: UPDATE proibido.';
  END IF;
  IF NEW.anonimizado_em IS NULL
     OR NEW.auditoria_dado_id IS DISTINCT FROM OLD.auditoria_dado_id
     OR NEW.auditoria_acao_id IS DISTINCT FROM OLD.auditoria_acao_id
     OR NEW.operacao IS DISTINCT FROM OLD.operacao
     OR NEW.tabela IS DISTINCT FROM OLD.tabela
     OR NEW.registro_id IS DISTINCT FROM OLD.registro_id
     OR NEW.data_acao IS DISTINCT FROM OLD.data_acao THEN
    RAISE EXCEPTION 'auditoria_dado: UPDATE so para redigir JSON e marcar anonimizado_em.';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_auditoria_dado_bloquear_update
BEFORE UPDATE ON flutz.auditoria_dado
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_auditoria_dado_bloquear_update();

CREATE OR REPLACE FUNCTION flutz.fn_auditoria_dado_bloquear_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'auditoria_dado: DELETE proibido. Use anonimizacao.';
END;
$$;

CREATE TRIGGER trg_auditoria_dado_bloquear_delete
BEFORE DELETE ON flutz.auditoria_dado
FOR EACH ROW
EXECUTE FUNCTION flutz.fn_auditoria_dado_bloquear_delete();
